/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/merc/dev/tools/Nim/lib -o /home/merc/dev/code/projects/nim/brainfuck/src/nimcache/brainfuck_brainfuck.o /home/merc/dev/code/projects/nim/brainfuck/src/nimcache/brainfuck_brainfuck.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Cell47505 Cell47505;
typedef struct TNimType TNimType;
typedef struct Cellseq47521 Cellseq47521;
typedef struct Gcheap49818 Gcheap49818;
typedef struct Gcstack49816 Gcstack49816;
typedef struct Cellset47517 Cellset47517;
typedef struct Pagedesc47513 Pagedesc47513;
typedef struct Memregion29688 Memregion29688;
typedef struct Smallchunk29640 Smallchunk29640;
typedef struct Llchunk29682 Llchunk29682;
typedef struct Bigchunk29642 Bigchunk29642;
typedef struct Intset29614 Intset29614;
typedef struct Trunk29610 Trunk29610;
typedef struct Avlnode29686 Avlnode29686;
typedef struct Gcstat49814 Gcstat49814;
typedef struct TY92139 TY92139;
typedef struct TY92050 TY92050;
typedef struct TNimNode TNimNode;
typedef struct Basechunk29638 Basechunk29638;
typedef struct Freecell29630 Freecell29630;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Cell47505  {
NI refcount;
TNimType* typ;
};
struct  Cellseq47521  {
NI len;
NI cap;
Cell47505** d;
};
struct  Cellset47517  {
NI counter;
NI max;
Pagedesc47513* head;
Pagedesc47513** data;
};
typedef Smallchunk29640* TY29703[512];
typedef Trunk29610* Trunkbuckets29612[256];
struct  Intset29614  {
Trunkbuckets29612 data;
};
struct  Memregion29688  {
NI minlargeobj;
NI maxlargeobj;
TY29703 freesmallchunks;
Llchunk29682* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29642* freechunkslist;
Intset29614 chunkstarts;
Avlnode29686* root;
Avlnode29686* deleted;
Avlnode29686* last;
Avlnode29686* freeavlnodes;
};
struct  Gcstat49814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap49818  {
Gcstack49816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47521 zct;
Cellseq47521 decstack;
Cellset47517 cycleroots;
Cellseq47521 tempstack;
NI recgclock;
Memregion29688 region;
Gcstat49814 stat;
};
struct  TY92139  {
NI HEX3Astate;
NI tapepos92072;
NI codepos92071;
NimStringDesc* code92005;
TY92050* tape92070;
};
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (NIM_BOOL skip, void* ClEnv);
void* ClEnv;
} TY92074;
typedef N_CLOSURE_PTR(NIM_BOOL, TMP40) (NIM_BOOL skip);
typedef N_CLOSURE_PTR(NIM_BOOL, TMP41) (NIM_BOOL skip);
struct  Gcstack49816  {
Gcstack49816* prev;
Gcstack49816* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY29619[8];
struct  Pagedesc47513  {
Pagedesc47513* next;
NI key;
TY29619 bits;
};
struct  Basechunk29638  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29640  {
  Basechunk29638 Sup;
Smallchunk29640* next;
Smallchunk29640* prev;
Freecell29630* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk29682  {
NI size;
NI acc;
Llchunk29682* next;
};
struct  Bigchunk29642  {
  Basechunk29638 Sup;
Bigchunk29642* next;
Bigchunk29642* prev;
NI align;
NF data;
};
struct  Trunk29610  {
Trunk29610* next;
NI key;
TY29619 bits;
};
typedef Avlnode29686* TY29693[2];
struct  Avlnode29686  {
TY29693 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell29630  {
Freecell29630* next;
NI zerofield;
};
struct TY92050 {
  TGenericSeq Sup;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, paramcount_135426)(void);
N_NIMCALL(NimStringDesc*, readfile_15466)(NimStringDesc* filename);
N_NIMCALL(NimStringDesc*, paramstr_135407)(NI i);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell47505*, usrtocell_51440)(void* usr);
static N_INLINE(void, rtladdzct_53001)(Cell47505* c);
N_NOINLINE(void, addzct_51417)(Cellseq47521* s, Cell47505* c);
N_NIMCALL(NimStringDesc*, readall_15463)(FILE* file);
N_NIMCALL(void, interpret_92003)(NimStringDesc* code);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP37)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(TY92050*, newseq_92045)(NI len);
N_CLOSURE(NIM_BOOL, run_92073)(NIM_BOOL skip, void* ClEnv);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
N_NIMCALL(void, xinc_92006)(NIM_CHAR* c);
N_NIMCALL(void, xdec_92019)(NIM_CHAR* c);
N_NIMCALL(void, write_15497)(FILE* f, NIM_CHAR c);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, brainfuckInit000)(void);
NIM_EXTERNC N_NOINLINE(void, brainfuckDatInit000)(void);
STRING_LITERAL(TMP17, "Welcome to brainfuck", 20);
NimStringDesc* code_139001;
extern Gcheap49818 gch_49859;
TNimType NTI92139; /* object */
extern TNimType NTI104; /* int */
TNimType NTI92141; /* range -1..0(int) */
extern TNimType NTI138; /* string */
extern TNimType NTI92050; /* seq[char] */
TNimType NTI92138; /* ref object */

static N_INLINE(Cell47505*, usrtocell_51440)(void* usr) {
	Cell47505* result;
	result = 0;
	result = ((Cell47505*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47505))))));
	return result;
}

static N_INLINE(void, rtladdzct_53001)(Cell47505* c) {
	addzct_51417((&gch_49859.zct), c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		Cell47505* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_51440(src);
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	{
		Cell47505* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_51440((*dest));
		{
			(*c).refcount -= ((NI) 8);
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			rtladdzct_53001(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}
N_NIMCALL(void, TMP37)(void* p, NI op) {
	TY92139* a;
	a = (TY92139*)p;
	nimGCvisit((void*)(*a).code92005, op);
	nimGCvisit((void*)(*a).tape92070, op);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell47505* c;
	c = usrtocell_51440(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_53001(c);
	}
	LA3: ;
}

N_NIMCALL(void, xinc_92006)(NIM_CHAR* c) {
	(*c) += ((NI) 1);
}

N_NIMCALL(void, xdec_92019)(NIM_CHAR* c) {
	(*c) -= ((NI) 1);
}

N_CLOSURE(NIM_BOOL, run_92073)(NIM_BOOL skip, void* ClEnv) {
	NIM_BOOL result;
	TY92139* HEX3Aenvp_92142;
{	result = 0;
	HEX3Aenvp_92142 = (TY92139*) ClEnv;
	{
		while (1) {
			NIM_BOOL LOC3;
			LOC3 = 0;
			LOC3 = (((NI) 0) <= (*HEX3Aenvp_92142).tapepos92072);
			if (!(LOC3)) goto LA4;
			LOC3 = ((*HEX3Aenvp_92142).codepos92071 < ((*HEX3Aenvp_92142).code92005 ? (*HEX3Aenvp_92142).code92005->Sup.len : 0));
			LA4: ;
			if (!LOC3) goto LA2;
			{
				if (!(((*HEX3Aenvp_92142).tape92070 ? (*HEX3Aenvp_92142).tape92070->Sup.len : 0) <= (*HEX3Aenvp_92142).tapepos92072)) goto LA7;
				(*HEX3Aenvp_92142).tape92070 = (TY92050*) incrSeqV2(&((*HEX3Aenvp_92142).tape92070)->Sup, sizeof(NIM_CHAR));
				(*HEX3Aenvp_92142).tape92070->data[(*HEX3Aenvp_92142).tape92070->Sup.len] = 0;
				++(*HEX3Aenvp_92142).tape92070->Sup.len;
			}
			LA7: ;
			{
				NI oldpos;
				if (!((NU8)((*HEX3Aenvp_92142).code92005->data[(*HEX3Aenvp_92142).codepos92071]) == (NU8)(91))) goto LA11;
				(*HEX3Aenvp_92142).codepos92071 += ((NI) 1);
				oldpos = (*HEX3Aenvp_92142).codepos92071;
				{
					while (1) {
						TY92074 LOC15;
						NIM_BOOL LOC16;
						memset((void*)(&LOC15), 0, sizeof(LOC15));
						LOC15.ClPrc = run_92073; LOC15.ClEnv = HEX3Aenvp_92142;
						LOC16 = 0;
						LOC16 = LOC15.ClEnv? LOC15.ClPrc(((NU8)((*HEX3Aenvp_92142).tape92070->data[(*HEX3Aenvp_92142).tapepos92072]) == (NU8)(0)), LOC15.ClEnv):((TMP40)(LOC15.ClPrc))(((NU8)((*HEX3Aenvp_92142).tape92070->data[(*HEX3Aenvp_92142).tapepos92072]) == (NU8)(0)));
						if (!LOC16) goto LA14;
						(*HEX3Aenvp_92142).codepos92071 = oldpos;
					} LA14: ;
				}
			}
			goto LA9;
			LA11: ;
			{
				if (!((NU8)((*HEX3Aenvp_92142).code92005->data[(*HEX3Aenvp_92142).codepos92071]) == (NU8)(93))) goto LA18;
				result = !(((NU8)((*HEX3Aenvp_92142).tape92070->data[(*HEX3Aenvp_92142).tapepos92072]) == (NU8)(0)));
				goto BeforeRet;
			}
			goto LA9;
			LA18: ;
			{
				if (!!(skip)) goto LA21;
				switch (((NU8)((*HEX3Aenvp_92142).code92005->data[(*HEX3Aenvp_92142).codepos92071]))) {
				case 43:
				{
					xinc_92006((&(*HEX3Aenvp_92142).tape92070->data[(*HEX3Aenvp_92142).tapepos92072]));
				}
				break;
				case 45:
				{
					xdec_92019((&(*HEX3Aenvp_92142).tape92070->data[(*HEX3Aenvp_92142).tapepos92072]));
				}
				break;
				case 62:
				{
					(*HEX3Aenvp_92142).tapepos92072 += ((NI) 1);
				}
				break;
				case 60:
				{
					(*HEX3Aenvp_92142).tapepos92072 -= ((NI) 1);
				}
				break;
				case 46:
				{
					write_15497(stdout, (*HEX3Aenvp_92142).tape92070->data[(*HEX3Aenvp_92142).tapepos92072]);
				}
				break;
				case 44:
				{
					(*HEX3Aenvp_92142).tape92070->data[(*HEX3Aenvp_92142).tapepos92072] = fgetc(stdin);
				}
				break;
				default:
				{
				}
				break;
				}
			}
			goto LA9;
			LA21: ;
			LA9: ;
			(*HEX3Aenvp_92142).codepos92071 += ((NI) 1);
		} LA2: ;
	}
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, interpret_92003)(NimStringDesc* code) {
	TY92139* HEX3Aenv_92147;
	NimStringDesc* LOC1;
	TY92074 LOC2;
	NIM_BOOL LOC3;
	HEX3Aenv_92147 = 0;
	HEX3Aenv_92147 = (TY92139*) newObj((&NTI92138), sizeof(TY92139));
	LOC1 = 0;
	LOC1 = (*HEX3Aenv_92147).code92005; (*HEX3Aenv_92147).code92005 = copyStringRC1(code);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	asgnRefNoCycle((void**) (&(*HEX3Aenv_92147).tape92070), newseq_92045(((NI) 0)));
	(*HEX3Aenv_92147).codepos92071 = ((NI) 0);
	(*HEX3Aenv_92147).tapepos92072 = ((NI) 0);
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.ClPrc = run_92073; LOC2.ClEnv = HEX3Aenv_92147;
	LOC3 = 0;
	LOC3 = LOC2.ClEnv? LOC2.ClPrc(NIM_FALSE, LOC2.ClEnv):((TMP41)(LOC2.ClPrc))(NIM_FALSE);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_macrosDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_osDatInit000();
	brainfuckDatInit000();
	stdlib_macrosInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_osInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	brainfuckInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, brainfuckInit000)(void) {
	printf("%s\012", ((NimStringDesc*) &TMP17)? (((NimStringDesc*) &TMP17))->data:"nil");
	fflush(stdout);
	{
		NI LOC3;
		NimStringDesc* LOC6;
		LOC3 = 0;
		LOC3 = paramcount_135426();
		if (!(((NI) 0) < LOC3)) goto LA4;
		LOC6 = 0;
		LOC6 = paramstr_135407(((NI) 1));
		asgnRefNoCycle((void**) (&code_139001), readfile_15466(LOC6));
	}
	goto LA1;
	LA4: ;
	{
		asgnRefNoCycle((void**) (&code_139001), readall_15463(stdin));
	}
	LA1: ;
	interpret_92003(code_139001);
}

NIM_EXTERNC N_NOINLINE(void, brainfuckDatInit000)(void) {
static TNimNode* TMP35[5];
static TNimNode TMP3[6];
NTI92139.size = sizeof(TY92139);
NTI92139.kind = 18;
NTI92139.base = 0;
NTI92139.flags = 2;
TMP35[0] = &TMP3[1];
NTI92141.size = sizeof(NI);
NTI92141.kind = 20;
NTI92141.base = (&NTI104);
NTI92141.flags = 3;
TMP3[1].kind = 1;
TMP3[1].offset = offsetof(TY92139, HEX3Astate);
TMP3[1].typ = (&NTI92141);
TMP3[1].name = ":state";
TMP35[1] = &TMP3[2];
TMP3[2].kind = 1;
TMP3[2].offset = offsetof(TY92139, tapepos92072);
TMP3[2].typ = (&NTI104);
TMP3[2].name = "tapePos92072";
TMP35[2] = &TMP3[3];
TMP3[3].kind = 1;
TMP3[3].offset = offsetof(TY92139, codepos92071);
TMP3[3].typ = (&NTI104);
TMP3[3].name = "codePos92071";
TMP35[3] = &TMP3[4];
TMP3[4].kind = 1;
TMP3[4].offset = offsetof(TY92139, code92005);
TMP3[4].typ = (&NTI138);
TMP3[4].name = "code92005";
TMP35[4] = &TMP3[5];
TMP3[5].kind = 1;
TMP3[5].offset = offsetof(TY92139, tape92070);
TMP3[5].typ = (&NTI92050);
TMP3[5].name = "tape92070";
TMP3[0].len = 5; TMP3[0].kind = 2; TMP3[0].sons = &TMP35[0];
NTI92139.node = &TMP3[0];
NTI92138.size = sizeof(TY92139*);
NTI92138.kind = 22;
NTI92138.base = (&NTI92139);
NTI92138.flags = 2;
NTI92138.marker = TMP37;
}

