/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/merc/dev/tools/Nim/lib -o /home/merc/dev/code/projects/nim/brainfuck/src/nimcache/stdlib_macros.o /home/merc/dev/code/projects/nim/brainfuck/src/nimcache/stdlib_macros.c */
#define NIM_INTBITS 64

#include "nimbase.h"
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void) {
}

