/* Generated by Nim Compiler v0.13.0 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/merc/dev/tools/Nim/lib -o /home/merc/dev/code/projects/nim/brainfuck/src/nimcache/stdlib_system.o /home/merc/dev/code/projects/nim/brainfuck/src/nimcache/stdlib_system.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <sys/mman.h>
#include <stdio.h>
#include <stdlib.h>
#include <setjmp.h>
#include <signal.h>
typedef struct Exception Exception;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Avlnode29686 Avlnode29686;
typedef struct Gcheap49818 Gcheap49818;
typedef struct Gcstack49816 Gcstack49816;
typedef struct Cellseq47521 Cellseq47521;
typedef struct Cell47505 Cell47505;
typedef struct Cellset47517 Cellset47517;
typedef struct Pagedesc47513 Pagedesc47513;
typedef struct Memregion29688 Memregion29688;
typedef struct Smallchunk29640 Smallchunk29640;
typedef struct Llchunk29682 Llchunk29682;
typedef struct Bigchunk29642 Bigchunk29642;
typedef struct Intset29614 Intset29614;
typedef struct Trunk29610 Trunk29610;
typedef struct Gcstat49814 Gcstat49814;
typedef struct Basechunk29638 Basechunk29638;
typedef struct Freecell29630 Freecell29630;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct TSafePoint TSafePoint;
typedef struct Ioerror3628 Ioerror3628;
typedef struct Systemerror3626 Systemerror3626;
typedef struct TNimObject TNimObject;
typedef struct Outofmemerror3650 Outofmemerror3650;
typedef struct Reraiseerror3660 Reraiseerror3660;
typedef struct Indexerror3652 Indexerror3652;
typedef struct TY92050 TY92050;
typedef struct Overflowerror3640 Overflowerror3640;
typedef struct Arithmeticerror3636 Arithmeticerror3636;
typedef N_NIMCALL_PTR(NIM_BOOL, TY10009) (Exception* e);
typedef N_NIMCALL_PTR(NIM_BOOL, TY10014) (Exception* e);
typedef N_NIMCALL_PTR(void, TY10019) (void);
typedef N_NIMCALL_PTR(void, TY3489) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3494) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3489 marker;
TY3494 deepcopy;
};
typedef Avlnode29686* TY29693[2];
struct  Avlnode29686  {
TY29693 link;
NI key;
NI upperbound;
NI level;
};
struct  Cellseq47521  {
NI len;
NI cap;
Cell47505** d;
};
struct  Cellset47517  {
NI counter;
NI max;
Pagedesc47513* head;
Pagedesc47513** data;
};
typedef Smallchunk29640* TY29703[512];
typedef Trunk29610* Trunkbuckets29612[256];
struct  Intset29614  {
Trunkbuckets29612 data;
};
struct  Memregion29688  {
NI minlargeobj;
NI maxlargeobj;
TY29703 freesmallchunks;
Llchunk29682* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk29642* freechunkslist;
Intset29614 chunkstarts;
Avlnode29686* root;
Avlnode29686* deleted;
Avlnode29686* last;
Avlnode29686* freeavlnodes;
};
struct  Gcstat49814  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap49818  {
Gcstack49816* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq47521 zct;
Cellseq47521 decstack;
Cellset47517 cycleroots;
Cellseq47521 tempstack;
NI recgclock;
Memregion29688 region;
Gcstat49814 stat;
};
struct  Basechunk29638  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk29640  {
  Basechunk29638 Sup;
Smallchunk29640* next;
Smallchunk29640* prev;
Freecell29630* freelist;
NI free;
NI acc;
NF data;
};
struct  Bigchunk29642  {
  Basechunk29638 Sup;
Bigchunk29642* next;
Bigchunk29642* prev;
NI align;
NF data;
};
typedef NI TY29619[8];
struct  Trunk29610  {
Trunk29610* next;
NI key;
TY29619 bits;
};
struct  Llchunk29682  {
NI size;
NI acc;
Llchunk29682* next;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Freecell29630  {
Freecell29630* next;
NI zerofield;
};
typedef N_NIMCALL_PTR(void, TY19201) (NimStringDesc* msg);
typedef TFrame* TY19803[128];
struct  Cell47505  {
NI refcount;
TNimType* typ;
};
struct  Pagedesc47513  {
Pagedesc47513* next;
NI key;
TY29619 bits;
};
typedef N_NIMCALL_PTR(void, Finalizer) (void* self);
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NimStringDesc* TY82613[5];
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror3626  {
  Exception Sup;
};
struct  Ioerror3628  {
  Systemerror3626 Sup;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY17811;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY17811 raiseAction;
};
typedef N_CLOSURE_PTR(NIM_BOOL, TMP26) (Exception* e);
struct  Outofmemerror3650  {
  Systemerror3626 Sup;
};
typedef NIM_CHAR TY21018[2001];
struct  Reraiseerror3660  {
  Exception Sup;
};
struct  Indexerror3652  {
  Exception Sup;
};
struct  Arithmeticerror3636  {
  Exception Sup;
};
struct  Overflowerror3640  {
  Arithmeticerror3636 Sup;
};
struct  Gcstack49816  {
Gcstack49816* prev;
Gcstack49816* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct TY92050 {
  TGenericSeq Sup;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
static N_INLINE(void, initallocator_11601)(void);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NIMCALL(void, initgc_11401)(void);
N_NIMCALL(void, init_47603)(Cellseq47521* s, NI cap);
N_NOCONV(void*, alloc0_7417)(NI size);
N_NIMCALL(void*, alloc0_46216)(Memregion29688* allocator, NI size);
N_NIMCALL(void*, alloc_46040)(Memregion29688* allocator, NI size);
N_NIMCALL(void*, rawalloc_36868)(Memregion29688* a, NI requestedsize);
static N_INLINE(NI, roundup_28201)(NI x, NI v);
N_NIMCALL(Smallchunk29640*, getsmallchunk_36212)(Memregion29688* a);
N_NIMCALL(Bigchunk29642*, getbigchunk_35414)(Memregion29688* a, NI size);
static N_INLINE(void, listremove_33202)(Bigchunk29642** head, Bigchunk29642* c);
N_NIMCALL(void, splitchunk_35209)(Memregion29688* a, Bigchunk29642* c, NI size);
static N_INLINE(void, updateprevsize_32268)(Memregion29688* a, Bigchunk29642* c, NI prevsize);
static N_INLINE(NIM_BOOL, isaccessible_32215)(Memregion29688* a, void* p);
N_NIMCALL(NIM_BOOL, contains_30932)(Intset29614* s, NI key);
N_NIMCALL(Trunk29610*, intsetget_30883)(Intset29614* t, NI key);
static N_INLINE(NI, pageindex_31375)(void* p);
N_NIMCALL(void, incl_30953)(Memregion29688* a, Intset29614* s, NI key);
N_NIMCALL(Trunk29610*, intsetput_30905)(Memregion29688* a, Intset29614* t, NI key);
N_NIMCALL(void*, llalloc_29843)(Memregion29688* a, NI size);
static N_INLINE(void*, osallocpages_29414)(NI size);
N_NOINLINE(void, raiseoutofmem_28034)(void);
static N_INLINE(void, inccurrmem_29802)(Memregion29688* a, NI bytes);
static N_INLINE(NI, pageindex_31370)(Basechunk29638* c);
static N_INLINE(void, listadd_34423)(Bigchunk29642** head, Bigchunk29642* c);
N_NIMCALL(Bigchunk29642*, requestoschunks_31387)(Memregion29688* a, NI size);
static N_INLINE(void, listadd_37816)(Smallchunk29640** head, Smallchunk29640* c);
static N_INLINE(void, listremove_40602)(Smallchunk29640** head, Smallchunk29640* c);
N_NIMCALL(void, add_30753)(Memregion29688* a, Avlnode29686** t, NI key, NI upperbound);
N_NIMCALL(Avlnode29686*, allocavlnode_30027)(Memregion29688* a, NI key, NI upperbound);
N_NIMCALL(void, skew_30734)(Avlnode29686** t);
N_NIMCALL(void, split_30739)(Avlnode29686** t);
N_NIMCALL(void, init_47618)(Cellset47517* s);
N_NOCONV(void, signalHandler)(int sig);
N_NIMCALL(void, showerrormessage_19406)(NCSTRING data);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(NimStringDesc*, toNimStr)(NCSTRING str, NI len);
N_NIMCALL(NimStringDesc*, rawNewStringNoInit)(NI space);
N_NIMCALL(void*, newObjNoInit)(TNimType* typ, NI size);
N_NIMCALL(void*, rawnewobj_57601)(TNimType* typ, NI size, Gcheap49818* gch);
N_NIMCALL(void, collectct_51807)(Gcheap49818* gch);
N_NOINLINE(NI, stacksize_71601)(void);
static N_INLINE(NI, getoccupiedmem_47430)(Memregion29688* a);
N_NIMCALL(void, collectctbody_75409)(Gcheap49818* gch);
static N_INLINE(void, prepareforinteriorpointerchecking_44888)(Memregion29688* a);
N_NIMCALL(NI, lowgauge_30612)(Avlnode29686* n);
N_NIMCALL(NI, highgauge_30629)(Avlnode29686* n);
N_CDECL(void, markstackandregisters_72837)(Gcheap49818* gch);
static N_INLINE(void, gcmark_70616)(Gcheap49818* gch, void* p);
static N_INLINE(Cell47505*, usrtocell_51440)(void* usr);
N_NIMCALL(void*, interiorallocatedptr_44892)(Memregion29688* a, void* p);
static N_INLINE(Basechunk29638*, pageaddr_31380)(void* p);
static N_INLINE(NIM_BOOL, chunkunused_31289)(Basechunk29638* c);
static N_INLINE(NIM_BOOL, issmallchunk_31269)(Basechunk29638* c);
N_NIMCALL(Avlnode29686*, inrange_30681)(Avlnode29686* root, NI key);
static N_INLINE(void, add_47583)(Cellseq47521* s, Cell47505* c);
N_NOCONV(void*, alloc_7401)(NI size);
N_NOCONV(void, dealloc_7448)(void* p);
N_NIMCALL(void, dealloc_46222)(Memregion29688* allocator, void* p);
N_NIMCALL(void, rawdealloc_43217)(Memregion29688* a, void* p);
N_NIMCALL(void, freebigchunk_32403)(Memregion29688* a, Bigchunk29642* c_32407);
N_NIMCALL(void, excl_30964)(Intset29614* s, NI key);
N_NIMCALL(void, freeoschunks_32007)(Memregion29688* a, void* p, NI size);
static N_INLINE(void, osdeallocpages_29420)(void* p, NI size);
static N_INLINE(void, deccurrmem_29816)(Memregion29688* a, NI bytes);
N_NIMCALL(void, del_30801)(Memregion29688* a, Avlnode29686** t, NI x);
static N_INLINE(void, deallocavlnode_30603)(Memregion29688* a, Avlnode29686* n);
N_NIMCALL(void, markthreadstacks_71203)(Gcheap49818* gch);
N_NIMCALL(NIM_BOOL, collectzct_70006)(Gcheap49818* gch);
static N_INLINE(NIM_BOOL, canbecycleroot_51458)(Cell47505* c);
N_NIMCALL(void, excl_48274)(Cellset47517* s, Cell47505* cell);
N_NIMCALL(Pagedesc47513*, cellsetget_47650)(Cellset47517* t, NI key);
static N_INLINE(NI, nexttry_47645)(NI h, NI maxhash);
N_NIMCALL(void, preparedealloc_52008)(Cell47505* cell);
static N_INLINE(void*, celltousr_51422)(Cell47505* cell);
N_NIMCALL(void, forallchildren_51814)(Cell47505* cell, NU8 op);
N_NIMCALL(void, forallchildrenaux_51822)(void* dest, TNimType* mt, NU8 op);
N_NIMCALL(void, dooperation_51818)(void* p, NU8 op);
static N_INLINE(void, decref_53401)(Cell47505* c);
static N_INLINE(void, rtladdzct_53001)(Cell47505* c);
N_NOINLINE(void, addzct_51417)(Cellseq47521* s, Cell47505* c);
static N_INLINE(void, rtladdcycleroot_52220)(Cell47505* c);
N_NOINLINE(void, incl_48247)(Cellset47517* s, Cell47505* cell);
N_NIMCALL(Pagedesc47513*, cellsetput_48041)(Cellset47517* t, NI key);
N_NIMCALL(void, cellsetenlarge_48003)(Cellset47517* t);
N_NIMCALL(void, cellsetrawinsert_47670)(Cellset47517* t, Pagedesc47513** data, Pagedesc47513* desc);
N_NIMCALL(void, markgray_67002)(Cell47505* s);
N_NIMCALL(void, scan_67401)(Cell47505* s);
N_NIMCALL(void, scanblack_67201)(Cell47505* s);
N_NIMCALL(void, collectwhite_67601)(Cell47505* s);
N_NIMCALL(NIM_BOOL, isallocatedptr_36602)(Memregion29688* a, void* p);
N_NIMCALL(void, freecycliccell_66215)(Gcheap49818* gch, Cell47505* c);
N_NIMCALL(void, forallslotsaux_56005)(void* dest, TNimNode* n, NU8 op);
N_NIMCALL(TNimNode*, selectbranch_27607)(void* aa, TNimNode* n);
N_NIMCALL(NI, getdiscriminant_27204)(void* aa, TNimNode* n);
N_NIMCALL(void, collectcycles_70220)(Gcheap49818* gch);
N_NIMCALL(void, markroots_67802)(Gcheap49818* gch);
N_NIMCALL(void, collectroots_70201)(Gcheap49818* gch);
N_NIMCALL(void, cellsetreset_56001)(Cellset47517* s);
N_NIMCALL(void, deinit_47626)(Cellset47517* s);
N_NIMCALL(NI, getoccupiedmem_8055)(void);
N_NIMCALL(NI, gettotalmem_8059)(void);
N_NIMCALL(NI, getfreemem_8057)(void);
N_NIMCALL(void, unmarkstackandregisters_75202)(Gcheap49818* gch);
static N_INLINE(void, addnewobjtozct_57074)(Cell47505* res, Gcheap49818* gch);
N_NIMCALL(void, writetostderr_19401)(NCSTRING msg);
N_NIMCALL(void, write_15501)(FILE* f, NCSTRING c);
N_NIMCALL(void, registersignalhandler_23002)(void);
N_NIMCALL(NI, getRefcount)(void* p);
N_NIMCALL(FILE*, open_15417)(NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(NIM_BOOL, open_15403)(FILE** f, NimStringDesc* filename, NU8 mode, NI bufsize);
static N_INLINE(void, sysfatal_15426)(NimStringDesc* message, NimStringDesc* arg) __attribute__((noreturn));
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP24)(void* p, NI op);
N_NIMCALL(void, TMP25)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(void, raiseexceptionaux_20601)(Exception* e);
static N_INLINE(void, pushCurrentException)(Exception* e);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_53819)(Cell47505* c);
static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_NOINLINE(NIM_BOOL, isobjslowpath_23734)(TNimType* obj, TNimType* subclass, TNimType** cache);
static N_INLINE(void, quitordebug_20404)(void);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_NIMCALL(NimStringDesc*, readall_15463)(FILE* file);
N_NIMCALL(NI, rawfilesize_81866)(FILE* file);
N_NIMCALL(NimStringDesc*, readallfile_81872)(FILE* file, NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NI, readbuffer_15554)(FILE* f, void* buffer, NI len);
N_NIMCALL(NIM_BOOL, endoffile_15454)(FILE* f);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(NI, resize_79201)(NI old);
N_NIMCALL(void*, growobj_66209)(void* old, NI newsize);
N_NIMCALL(void*, growobj_63403)(void* old, NI newsize, Gcheap49818* gch);
N_NOINLINE(void, raiseeio_81205)(NimStringDesc* msg) __attribute__((noreturn));
static N_INLINE(void, sysfatal_81210)(NimStringDesc* message) __attribute__((noreturn));
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_NIMCALL(void*, newObjRC1)(TNimType* typ, NI size);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(NimStringDesc*, readallbuffer_81858)(FILE* file);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, popSafePoint)(void);
N_NIMCALL(void, reraiseException)(void);
static N_INLINE(void, sysfatal_21217)(NimStringDesc* message) __attribute__((noreturn));
N_NIMCALL(void, TMP31)(void* p, NI op);
N_NIMCALL(void, TMP33)(void* p, NI op);
N_NIMCALL(void, TMP36)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, sysfatal_23862)(NimStringDesc* message) __attribute__((noreturn));
N_NIMCALL(void, TMP38)(void* p, NI op);
N_NIMCALL(NI, mulInt)(NI a, NI b);
STRING_LITERAL(TMP2, "out of memory", 13);
STRING_LITERAL(TMP18, "rb", 2);
STRING_LITERAL(TMP19, "wb", 2);
STRING_LITERAL(TMP20, "w+b", 3);
STRING_LITERAL(TMP21, "r+b", 3);
STRING_LITERAL(TMP22, "ab", 2);
NIM_CONST TY82613 Formatopen_82610 = {((NimStringDesc*) &TMP18),
((NimStringDesc*) &TMP19),
((NimStringDesc*) &TMP20),
((NimStringDesc*) &TMP21),
((NimStringDesc*) &TMP22)}
;
STRING_LITERAL(TMP27, "cannot open: ", 13);
STRING_LITERAL(TMP29, "error while reading from file", 29);
STRING_LITERAL(TMP30, "", 0);
STRING_LITERAL(TMP32, "no exception to reraise", 23);
STRING_LITERAL(TMP39, "over- or underflow", 18);
NIM_BOOL nimvm_5751;
NI nim_program_result;
TY10009 globalraisehook_10013;
TY10014 localraisehook_10018;
TY10019 outofmemhook_10021;
TNimType strdesc_12203;
TY19201 errormessagewriter_19204;
TFrame* frameptr_19436;
TSafePoint* exchandler_19437;
Exception* currexception_19439;
TY19803 tempframes_19804;
Avlnode29686 bottomdata_29719;
Avlnode29686* bottom_29720;
Gcheap49818 gch_49859;
NIM_BOOL localgcinitialized_71624;
NIM_CHAR decimalpoint_80605;
TNimType NTI3608; /* RootObj */
TNimType NTI3624; /* Exception */
TNimType NTI10010; /* ref Exception */
TNimType NTI140; /* cstring */
TNimType NTI138; /* string */
TNimType NTI3626; /* SystemError */
TNimType NTI3628; /* IOError */
TNimType NTI15435; /* ref IOError */
TNimType NTI3650; /* OutOfMemError */
static TNimType* Nim_OfCheck_CACHE1[2];
TNimType NTI3660; /* ReraiseError */
TNimType NTI21224; /* ref ReraiseError */
TNimType NTI3652; /* IndexError */
TNimType NTI135415; /* ref IndexError */
TNimType NTI104; /* int */
TNimType NTI136; /* char */
TNimType NTI92050; /* seq[char] */
TNimType NTI3636; /* ArithmeticError */
TNimType NTI3640; /* OverflowError */
TNimType NTI23869; /* ref OverflowError */

static N_INLINE(void, initallocator_11601)(void) {
	bottom_29720 = (&bottomdata_29719);
	(*bottom_29720).link[(((NI) 0))- 0] = bottom_29720;
	(*bottom_29720).link[(((NI) 1))- 0] = bottom_29720;
}

N_NOINLINE(void, setStackBottom)(void* thestackbottom) {
	{
		if (!(gch_49859.stackbottom == NIM_NIL)) goto LA3;
		gch_49859.stackbottom = thestackbottom;
	}
	goto LA1;
	LA3: ;
	{
		NI a;
		NI b;
		a = ((NI) (thestackbottom));
		b = ((NI) (gch_49859.stackbottom));
		gch_49859.stackbottom = ((void*) (((a >= b) ? a : b)));
	}
	LA1: ;
}

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) ((&locals)));
	setStackBottom(locals);
}

static N_INLINE(NI, roundup_28201)(NI x, NI v) {
	NI result;
	result = 0;
	result = (NI)((NI)(x + (NI)(v - ((NI) 1))) & (NI)((NU64) ~((NI)(v - ((NI) 1)))));
	return result;
}

static N_INLINE(void, listremove_33202)(Bigchunk29642** head, Bigchunk29642* c) {
	{
		if (!(c == (*head))) goto LA3;
		(*head) = (*c).next;
		{
			if (!!(((*head) == NIM_NIL))) goto LA7;
			(*(*head)).prev = NIM_NIL;
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		(*(*c).prev).next = (*c).next;
		{
			if (!!(((*c).next == NIM_NIL))) goto LA12;
			(*(*c).next).prev = (*c).prev;
		}
		LA12: ;
	}
	LA1: ;
	(*c).next = NIM_NIL;
	(*c).prev = NIM_NIL;
}

N_NIMCALL(Trunk29610*, intsetget_30883)(Intset29614* t, NI key) {
	Trunk29610* result;
	Trunk29610* it;
{	result = 0;
	it = (*t).data[((NI)(key & ((NI) 255)))- 0];
	{
		while (1) {
			if (!!((it == NIM_NIL))) goto LA2;
			{
				if (!((*it).key == key)) goto LA5;
				result = it;
				goto BeforeRet;
			}
			LA5: ;
			it = (*it).next;
		} LA2: ;
	}
	result = NIM_NIL;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NIM_BOOL, contains_30932)(Intset29614* s, NI key) {
	NIM_BOOL result;
	Trunk29610* t;
	result = 0;
	t = intsetget_30883(s, (NI)((NU64)(key) >> (NU64)(((NI) 9))));
	{
		NI u;
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)(key & ((NI) 511));
		result = !(((NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63))))))) == ((NI) 0)));
	}
	goto LA1;
	LA3: ;
	{
		result = NIM_FALSE;
	}
	LA1: ;
	return result;
}

static N_INLINE(NI, pageindex_31375)(void* p) {
	NI result;
	result = 0;
	result = (NI)((NU64)(((NI) (p))) >> (NU64)(((NI) 12)));
	return result;
}

static N_INLINE(NIM_BOOL, isaccessible_32215)(Memregion29688* a, void* p) {
	NIM_BOOL result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = pageindex_31375(p);
	result = contains_30932((&(*a).chunkstarts), LOC1);
	return result;
}

static N_INLINE(void, updateprevsize_32268)(Memregion29688* a, Bigchunk29642* c, NI prevsize) {
	Basechunk29638* ri;
	ri = ((Basechunk29638*) ((NI)((NU64)(((NI) (c))) + (NU64)((*c).Sup.size))));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = isaccessible_32215((&(*a)), ((void*) (ri)));
		if (!LOC3) goto LA4;
		(*ri).prevsize = prevsize;
	}
	LA4: ;
}

N_NOINLINE(void, raiseoutofmem_28034)(void) {
	{
		if (!!((outofmemhook_10021 == NIM_NIL))) goto LA3;
		outofmemhook_10021();
	}
	LA3: ;
	printf("%s\012", ((NimStringDesc*) &TMP2)? (((NimStringDesc*) &TMP2))->data:"nil");
	fflush(stdout);
	exit(((NI) 1));
}

static N_INLINE(void*, osallocpages_29414)(NI size) {
	void* result;
	result = 0;
	result = mmap(NIM_NIL, size, ((int) 3), (NI32)(((NI32) 2) | MAP_ANONYMOUS), ((int) -1), ((NI) 0));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (result == NIM_NIL);
		if (LOC3) goto LA4;
		LOC3 = (result == ((void*) -1));
		LA4: ;
		if (!LOC3) goto LA5;
		raiseoutofmem_28034();
	}
	LA5: ;
	return result;
}

static N_INLINE(void, inccurrmem_29802)(Memregion29688* a, NI bytes) {
	(*a).currmem += bytes;
}

N_NIMCALL(void*, llalloc_29843)(Memregion29688* a, NI size) {
	void* result;
	result = 0;
	{
		NIM_BOOL LOC3;
		Llchunk29682* old;
		void* LOC7;
		LOC3 = 0;
		LOC3 = ((*a).llmem == NIM_NIL);
		if (LOC3) goto LA4;
		LOC3 = ((*(*a).llmem).size < size);
		LA4: ;
		if (!LOC3) goto LA5;
		old = (*a).llmem;
		LOC7 = 0;
		LOC7 = osallocpages_29414(((NI) 4096));
		(*a).llmem = ((Llchunk29682*) (LOC7));
		inccurrmem_29802(a, ((NI) 4096));
		(*(*a).llmem).size = (NI)(((NI) 4096) - ((NI)sizeof(Llchunk29682)));
		(*(*a).llmem).acc = ((NI)sizeof(Llchunk29682));
		(*(*a).llmem).next = old;
	}
	LA5: ;
	result = ((void*) ((NI)(((NI) ((*a).llmem)) + (*(*a).llmem).acc)));
	(*(*a).llmem).size -= size;
	(*(*a).llmem).acc += size;
	zeroMem(result, ((NI) (size)));
	return result;
}

N_NIMCALL(Trunk29610*, intsetput_30905)(Memregion29688* a, Intset29614* t, NI key) {
	Trunk29610* result;
	result = 0;
	result = intsetget_30883((&(*t)), key);
	{
		void* LOC5;
		if (!(result == NIM_NIL)) goto LA3;
		LOC5 = 0;
		LOC5 = llalloc_29843(a, ((NI)sizeof(Trunk29610)));
		result = ((Trunk29610*) (LOC5));
		(*result).next = (*t).data[((NI)(key & ((NI) 255)))- 0];
		(*t).data[((NI)(key & ((NI) 255)))- 0] = result;
		(*result).key = key;
	}
	LA3: ;
	return result;
}

N_NIMCALL(void, incl_30953)(Memregion29688* a, Intset29614* s, NI key) {
	Trunk29610* t;
	NI u;
	t = intsetput_30905(a, s, (NI)((NU64)(key) >> (NU64)(((NI) 9))));
	u = (NI)(key & ((NI) 511));
	(*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] | (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63)))))));
}

static N_INLINE(NI, pageindex_31370)(Basechunk29638* c) {
	NI result;
	result = 0;
	result = (NI)((NU64)(((NI) (c))) >> (NU64)(((NI) 12)));
	return result;
}

static N_INLINE(void, listadd_34423)(Bigchunk29642** head, Bigchunk29642* c) {
	(*c).next = (*head);
	{
		if (!!(((*head) == NIM_NIL))) goto LA3;
		(*(*head)).prev = c;
	}
	LA3: ;
	(*head) = c;
}

N_NIMCALL(void, splitchunk_35209)(Memregion29688* a, Bigchunk29642* c, NI size) {
	Bigchunk29642* rest;
	Basechunk29638* LOC1;
	NI LOC2;
	rest = ((Bigchunk29642*) ((NI)((NU64)(((NI) (c))) + (NU64)(size))));
	(*rest).Sup.size = (NI)((*c).Sup.size - size);
	(*rest).Sup.used = NIM_FALSE;
	(*rest).next = NIM_NIL;
	(*rest).prev = NIM_NIL;
	(*rest).Sup.prevsize = size;
	updateprevsize_32268(a, c, (*rest).Sup.size);
	(*c).Sup.size = size;
	LOC1 = 0;
	LOC1 = &rest->Sup;
	LOC2 = 0;
	LOC2 = pageindex_31370(LOC1);
	incl_30953(a, (&(*a).chunkstarts), LOC2);
	listadd_34423(&(*a).freechunkslist, rest);
}

N_NIMCALL(Bigchunk29642*, requestoschunks_31387)(Memregion29688* a, NI size) {
	Bigchunk29642* result;
	void* LOC1;
	NI nxt;
	Basechunk29638* next;
	NI lastsize;
	NI prv;
	Basechunk29638* prev;
	result = 0;
	inccurrmem_29802(a, size);
	(*a).freemem += size;
	LOC1 = 0;
	LOC1 = osallocpages_29414(size);
	result = ((Bigchunk29642*) (LOC1));
	(*result).next = NIM_NIL;
	(*result).prev = NIM_NIL;
	(*result).Sup.used = NIM_FALSE;
	(*result).Sup.size = size;
	nxt = (NI)((NU64)(((NI) (result))) + (NU64)(size));
	next = ((Basechunk29638*) (nxt));
	{
		NI LOC4;
		NIM_BOOL LOC5;
		LOC4 = 0;
		LOC4 = pageindex_31370(next);
		LOC5 = 0;
		LOC5 = contains_30932((&(*a).chunkstarts), LOC4);
		if (!LOC5) goto LA6;
		(*next).prevsize = size;
	}
	LA6: ;
	{
		if (!!(((*a).lastsize == ((NI) 0)))) goto LA10;
		lastsize = (*a).lastsize;
	}
	goto LA8;
	LA10: ;
	{
		lastsize = ((NI) 4096);
	}
	LA8: ;
	prv = (NI)((NU64)(((NI) (result))) - (NU64)(lastsize));
	prev = ((Basechunk29638*) (prv));
	{
		NIM_BOOL LOC15;
		NI LOC16;
		LOC15 = 0;
		LOC16 = 0;
		LOC16 = pageindex_31370(prev);
		LOC15 = contains_30932((&(*a).chunkstarts), LOC16);
		if (!(LOC15)) goto LA17;
		LOC15 = ((*prev).size == lastsize);
		LA17: ;
		if (!LOC15) goto LA18;
		(*result).Sup.prevsize = lastsize;
	}
	goto LA13;
	LA18: ;
	{
		(*result).Sup.prevsize = ((NI) 0);
	}
	LA13: ;
	(*a).lastsize = size;
	return result;
}

N_NIMCALL(Bigchunk29642*, getbigchunk_35414)(Memregion29688* a, NI size) {
	Bigchunk29642* result;
	Basechunk29638* LOC16;
	NI LOC17;
	result = 0;
	result = (*a).freechunkslist;
	{
		{
			while (1) {
				if (!!((result == NIM_NIL))) goto LA3;
				{
					if (!((*result).Sup.size == size)) goto LA6;
					listremove_33202(&(*a).freechunkslist, result);
					goto LA1;
				}
				goto LA4;
				LA6: ;
				{
					if (!(size < (*result).Sup.size)) goto LA9;
					listremove_33202(&(*a).freechunkslist, result);
					splitchunk_35209(a, result, size);
					goto LA1;
				}
				goto LA4;
				LA9: ;
				LA4: ;
				result = (*result).next;
			} LA3: ;
		}
		{
			if (!(size < ((NI) 524288))) goto LA13;
			result = requestoschunks_31387(a, ((NI) 524288));
			splitchunk_35209(a, result, size);
		}
		goto LA11;
		LA13: ;
		{
			result = requestoschunks_31387(a, size);
		}
		LA11: ;
	} LA1: ;
	(*result).Sup.prevsize = ((NI) 0);
	(*result).Sup.used = NIM_TRUE;
	LOC16 = 0;
	LOC16 = &result->Sup;
	LOC17 = 0;
	LOC17 = pageindex_31370(LOC16);
	incl_30953(a, (&(*a).chunkstarts), LOC17);
	(*a).freemem -= size;
	return result;
}

N_NIMCALL(Smallchunk29640*, getsmallchunk_36212)(Memregion29688* a) {
	Smallchunk29640* result;
	Bigchunk29642* res;
	result = 0;
	res = getbigchunk_35414(a, ((NI) 4096));
	result = ((Smallchunk29640*) (res));
	return result;
}

static N_INLINE(void, listadd_37816)(Smallchunk29640** head, Smallchunk29640* c) {
	(*c).next = (*head);
	{
		if (!!(((*head) == NIM_NIL))) goto LA3;
		(*(*head)).prev = c;
	}
	LA3: ;
	(*head) = c;
}

static N_INLINE(void, listremove_40602)(Smallchunk29640** head, Smallchunk29640* c) {
	{
		if (!(c == (*head))) goto LA3;
		(*head) = (*c).next;
		{
			if (!!(((*head) == NIM_NIL))) goto LA7;
			(*(*head)).prev = NIM_NIL;
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		(*(*c).prev).next = (*c).next;
		{
			if (!!(((*c).next == NIM_NIL))) goto LA12;
			(*(*c).next).prev = (*c).prev;
		}
		LA12: ;
	}
	LA1: ;
	(*c).next = NIM_NIL;
	(*c).prev = NIM_NIL;
}

N_NIMCALL(Avlnode29686*, allocavlnode_30027)(Memregion29688* a, NI key, NI upperbound) {
	Avlnode29686* result;
	result = 0;
	{
		if (!!(((*a).freeavlnodes == NIM_NIL))) goto LA3;
		result = (*a).freeavlnodes;
		(*a).freeavlnodes = (*(*a).freeavlnodes).link[(((NI) 0))- 0];
	}
	goto LA1;
	LA3: ;
	{
		void* LOC6;
		LOC6 = 0;
		LOC6 = llalloc_29843(a, ((NI)sizeof(Avlnode29686)));
		result = ((Avlnode29686*) (LOC6));
	}
	LA1: ;
	(*result).key = key;
	(*result).upperbound = upperbound;
	(*result).link[(((NI) 0))- 0] = bottom_29720;
	(*result).link[(((NI) 1))- 0] = bottom_29720;
	(*result).level = ((NI) 1);
	return result;
}

N_NIMCALL(void, skew_30734)(Avlnode29686** t) {
	{
		Avlnode29686* temp;
		if (!((*(*(*t)).link[(((NI) 0))- 0]).level == (*(*t)).level)) goto LA3;
		temp = (*t);
		(*t) = (*(*t)).link[(((NI) 0))- 0];
		(*temp).link[(((NI) 0))- 0] = (*(*t)).link[(((NI) 1))- 0];
		(*(*t)).link[(((NI) 1))- 0] = temp;
	}
	LA3: ;
}

N_NIMCALL(void, split_30739)(Avlnode29686** t) {
	{
		Avlnode29686* temp;
		if (!((*(*(*(*t)).link[(((NI) 1))- 0]).link[(((NI) 1))- 0]).level == (*(*t)).level)) goto LA3;
		temp = (*t);
		(*t) = (*(*t)).link[(((NI) 1))- 0];
		(*temp).link[(((NI) 1))- 0] = (*(*t)).link[(((NI) 0))- 0];
		(*(*t)).link[(((NI) 0))- 0] = temp;
		(*(*t)).level += ((NI) 1);
	}
	LA3: ;
}

N_NIMCALL(void, add_30753)(Memregion29688* a, Avlnode29686** t, NI key, NI upperbound) {
	{
		if (!((*t) == bottom_29720)) goto LA3;
		(*t) = allocavlnode_30027(a, key, upperbound);
	}
	goto LA1;
	LA3: ;
	{
		{
			if (!((NU64)(key) < (NU64)((*(*t)).key))) goto LA8;
			add_30753(a, &(*(*t)).link[(((NI) 0))- 0], key, upperbound);
		}
		goto LA6;
		LA8: ;
		{
			if (!((NU64)((*(*t)).key) < (NU64)(key))) goto LA11;
			add_30753(a, &(*(*t)).link[(((NI) 1))- 0], key, upperbound);
		}
		goto LA6;
		LA11: ;
		{
		}
		LA6: ;
		skew_30734(t);
		split_30739(t);
	}
	LA1: ;
}

N_NIMCALL(void*, rawalloc_36868)(Memregion29688* a, NI requestedsize) {
	void* result;
	NI size;
	result = 0;
	size = roundup_28201(requestedsize, ((NI) 8));
	{
		NI s;
		Smallchunk29640* c;
		if (!(size <= (NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk29640)) - ((NI) 8))))) goto LA3;
		s = (NI)(size / ((NI) 8));
		c = (*a).freesmallchunks[(s)- 0];
		{
			if (!(c == NIM_NIL)) goto LA7;
			c = getsmallchunk_36212(a);
			(*c).freelist = NIM_NIL;
			(*c).Sup.size = size;
			(*c).acc = size;
			(*c).free = (NI)((NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk29640)) - ((NI) 8))) - size);
			(*c).next = NIM_NIL;
			(*c).prev = NIM_NIL;
			listadd_37816(&(*a).freesmallchunks[(s)- 0], c);
			result = ((void*) ((&(*c).data)));
		}
		goto LA5;
		LA7: ;
		{
			{
				if (!((*c).freelist == NIM_NIL)) goto LA12;
				result = ((void*) ((NI)((NU64)(((NI) ((&(*c).data)))) + (NU64)((*c).acc))));
				(*c).acc += size;
			}
			goto LA10;
			LA12: ;
			{
				result = ((void*) ((*c).freelist));
				(*c).freelist = (*(*c).freelist).next;
			}
			LA10: ;
			(*c).free -= size;
		}
		LA5: ;
		{
			if (!((*c).free < size)) goto LA17;
			listremove_40602(&(*a).freesmallchunks[(s)- 0], c);
		}
		LA17: ;
	}
	goto LA1;
	LA3: ;
	{
		Bigchunk29642* c;
		size = roundup_28201((NI)(requestedsize + (NI)(((NI)sizeof(Bigchunk29642)) - ((NI) 8))), ((NI) 4096));
		c = getbigchunk_35414(a, size);
		result = ((void*) ((&(*c).data)));
		{
			if (!((*a).root == NIM_NIL)) goto LA22;
			(*a).root = bottom_29720;
		}
		LA22: ;
		add_30753(a, &(*a).root, ((NI) (result)), (NI)((NU64)(((NI) (result))) + (NU64)(size)));
	}
	LA1: ;
	return result;
}

N_NIMCALL(void*, alloc_46040)(Memregion29688* allocator, NI size) {
	void* result;
	result = 0;
	result = rawalloc_36868(allocator, (NI)(((NI) (size)) + ((NI)sizeof(Freecell29630))));
	(*((Freecell29630*) (result))).zerofield = ((NI) 1);
	result = ((void*) ((NI)((NU64)(((NI) (result))) + (NU64)(((NI)sizeof(Freecell29630))))));
	return result;
}

N_NIMCALL(void*, alloc0_46216)(Memregion29688* allocator, NI size) {
	void* result;
	result = 0;
	result = alloc_46040(allocator, size);
	zeroMem(result, size);
	return result;
}

N_NOCONV(void*, alloc0_7417)(NI size) {
	void* result;
	result = 0;
	result = alloc0_46216((&gch_49859.region), size);
	return result;
}

N_NIMCALL(void, init_47603)(Cellseq47521* s, NI cap) {
	void* LOC1;
	(*s).len = ((NI) 0);
	(*s).cap = cap;
	LOC1 = 0;
	LOC1 = alloc0_7417(((NI) ((NI)(cap * ((NI) 8)))));
	(*s).d = ((Cell47505**) (LOC1));
}

N_NIMCALL(void, init_47618)(Cellset47517* s) {
	void* LOC1;
	LOC1 = 0;
	LOC1 = alloc0_7417(((NI) 8192));
	(*s).data = ((Pagedesc47513**) (LOC1));
	(*s).max = ((NI) 1023);
	(*s).counter = ((NI) 0);
	(*s).head = NIM_NIL;
}

N_NIMCALL(void, initgc_11401)(void) {
	gch_49859.cyclethreshold = ((NI) 4194304);
	gch_49859.stat.stackscans = ((NI) 0);
	gch_49859.stat.cyclecollections = ((NI) 0);
	gch_49859.stat.maxthreshold = ((NI) 0);
	gch_49859.stat.maxstacksize = ((NI) 0);
	gch_49859.stat.maxstackcells = ((NI) 0);
	gch_49859.stat.cycletablesize = ((NI) 0);
	init_47603((&gch_49859.zct), ((NI) 1024));
	init_47603((&gch_49859.tempstack), ((NI) 1024));
	init_47618((&gch_49859.cycleroots));
	init_47603((&gch_49859.decstack), ((NI) 1024));
}

N_NOINLINE(NI, stacksize_71601)(void) {
	NI result;
	void* volatile stacktop;
	result = 0;
	stacktop = 0;
	result = ((NI)(((NI) ((&stacktop))) - ((NI) (gch_49859.stackbottom))) > 0? ((NI)(((NI) ((&stacktop))) - ((NI) (gch_49859.stackbottom)))) : -((NI)(((NI) ((&stacktop))) - ((NI) (gch_49859.stackbottom)))));
	return result;
}

static N_INLINE(NI, getoccupiedmem_47430)(Memregion29688* a) {
	NI result;
	result = 0;
	result = (NI)((*a).currmem - (*a).freemem);
	return result;
}

N_NIMCALL(NI, lowgauge_30612)(Avlnode29686* n) {
	NI result;
	Avlnode29686* it;
	result = 0;
	it = n;
	{
		while (1) {
			if (!!((it == bottom_29720))) goto LA2;
			result = (*it).key;
			it = (*it).link[(((NI) 0))- 0];
		} LA2: ;
	}
	return result;
}

N_NIMCALL(NI, highgauge_30629)(Avlnode29686* n) {
	NI result;
	Avlnode29686* it;
	result = 0;
	result = ((NI) -1);
	it = n;
	{
		while (1) {
			if (!!((it == bottom_29720))) goto LA2;
			result = (*it).upperbound;
			it = (*it).link[(((NI) 1))- 0];
		} LA2: ;
	}
	return result;
}

static N_INLINE(void, prepareforinteriorpointerchecking_44888)(Memregion29688* a) {
	(*a).minlargeobj = lowgauge_30612((*a).root);
	(*a).maxlargeobj = highgauge_30629((*a).root);
}

static N_INLINE(Cell47505*, usrtocell_51440)(void* usr) {
	Cell47505* result;
	result = 0;
	result = ((Cell47505*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell47505))))));
	return result;
}

static N_INLINE(Basechunk29638*, pageaddr_31380)(void* p) {
	Basechunk29638* result;
	result = 0;
	result = ((Basechunk29638*) ((NI)(((NI) (p)) & ((NI) -4096))));
	return result;
}

static N_INLINE(NIM_BOOL, chunkunused_31289)(Basechunk29638* c) {
	NIM_BOOL result;
	result = 0;
	result = !((*c).used);
	return result;
}

static N_INLINE(NIM_BOOL, issmallchunk_31269)(Basechunk29638* c) {
	NIM_BOOL result;
{	result = 0;
	result = ((*c).size <= (NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk29640)) - ((NI) 8))));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(Avlnode29686*, inrange_30681)(Avlnode29686* root, NI key) {
	Avlnode29686* result;
	Avlnode29686* it;
{	result = 0;
	it = root;
	{
		while (1) {
			if (!!((it == bottom_29720))) goto LA2;
			{
				NIM_BOOL LOC5;
				LOC5 = 0;
				LOC5 = ((NU64)((*it).key) <= (NU64)(key));
				if (!(LOC5)) goto LA6;
				LOC5 = ((NU64)(key) < (NU64)((*it).upperbound));
				LA6: ;
				if (!LOC5) goto LA7;
				result = it;
				goto BeforeRet;
			}
			LA7: ;
			it = (*it).link[(((NU64)((*it).key) < (NU64)(key)))- 0];
		} LA2: ;
	}
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void*, interiorallocatedptr_44892)(Memregion29688* a, void* p) {
	void* result;
	result = 0;
	{
		NIM_BOOL LOC3;
		Basechunk29638* c_44897;
		LOC3 = 0;
		LOC3 = isaccessible_32215(a, p);
		if (!LOC3) goto LA4;
		c_44897 = pageaddr_31380(p);
		{
			NIM_BOOL LOC8;
			LOC8 = 0;
			LOC8 = chunkunused_31289(c_44897);
			if (!!(LOC8)) goto LA9;
			{
				NIM_BOOL LOC13;
				Smallchunk29640* c;
				NI offset;
				LOC13 = 0;
				LOC13 = issmallchunk_31269(c_44897);
				if (!LOC13) goto LA14;
				c = ((Smallchunk29640*) (c_44897));
				offset = (NI)((NU64)(((NI) ((NI)(((NI) (p)) & ((NI) 4095))))) - (NU64)((NI)(((NI)sizeof(Smallchunk29640)) - ((NI) 8))));
				{
					Freecell29630* d;
					if (!((NU64)(offset) < (NU64)((*c).acc))) goto LA18;
					d = ((Freecell29630*) ((NI)((NU64)((NI)((NU64)(((NI) ((&(*c).data)))) + (NU64)(offset))) - (NU64)((NI)((NU64)(offset) % (NU64)((*c).Sup.size))))));
					{
						if (!((NU64)(((NI) 1)) < (NU64)((*d).zerofield))) goto LA22;
						result = ((void*) (d));
					}
					LA22: ;
				}
				LA18: ;
			}
			goto LA11;
			LA14: ;
			{
				Bigchunk29642* c;
				NF* d;
				c = ((Bigchunk29642*) (c_44897));
				d = (&(*c).data);
				{
					NIM_BOOL LOC27;
					LOC27 = 0;
					LOC27 = (((void*) (d)) <= p);
					if (!(LOC27)) goto LA28;
					LOC27 = ((NU64)(((NI) 1)) < (NU64)((*((Freecell29630*) (d))).zerofield));
					LA28: ;
					if (!LOC27) goto LA29;
					result = ((void*) (d));
				}
				LA29: ;
			}
			LA11: ;
		}
		LA9: ;
	}
	goto LA1;
	LA4: ;
	{
		NI q;
		q = ((NI) (p));
		{
			NIM_BOOL LOC34;
			Avlnode29686* avlnode;
			LOC34 = 0;
			LOC34 = ((NU64)((*a).minlargeobj) <= (NU64)(q));
			if (!(LOC34)) goto LA35;
			LOC34 = ((NU64)(q) <= (NU64)((*a).maxlargeobj));
			LA35: ;
			if (!LOC34) goto LA36;
			avlnode = inrange_30681((*a).root, q);
			{
				void* k;
				Bigchunk29642* c;
				Basechunk29638* LOC42;
				if (!!((avlnode == NIM_NIL))) goto LA40;
				k = ((void*) ((*avlnode).key));
				LOC42 = 0;
				LOC42 = pageaddr_31380(k);
				c = ((Bigchunk29642*) (LOC42));
				{
					if (!((NU64)(((NI) 1)) < (NU64)((*((Freecell29630*) (k))).zerofield))) goto LA45;
					result = k;
				}
				LA45: ;
			}
			LA40: ;
		}
		LA36: ;
	}
	LA1: ;
	return result;
}

N_NOCONV(void*, alloc_7401)(NI size) {
	void* result;
	result = 0;
	result = alloc_46040((&gch_49859.region), size);
	return result;
}

N_NIMCALL(void, excl_30964)(Intset29614* s, NI key) {
	Trunk29610* t;
	t = intsetget_30883((&(*s)), (NI)((NU64)(key) >> (NU64)(((NI) 9))));
	{
		NI u;
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)(key & ((NI) 511));
		(*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(((NI) (u))) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64) ~((NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(((NI) (u)) & ((NI) 63)))))))));
	}
	LA3: ;
}

static N_INLINE(void, osdeallocpages_29420)(void* p, NI size) {
	munmap(p, size);
}

static N_INLINE(void, deccurrmem_29816)(Memregion29688* a, NI bytes) {
	(*a).maxmem = (((*a).maxmem >= (*a).currmem) ? (*a).maxmem : (*a).currmem);
	(*a).currmem -= bytes;
}

N_NIMCALL(void, freeoschunks_32007)(Memregion29688* a, void* p, NI size) {
	Basechunk29638* c;
	NI nxt;
	Basechunk29638* next;
	NI LOC7;
	c = ((Basechunk29638*) (p));
	nxt = (NI)((NU64)(((NI) (p))) + (NU64)((*c).size));
	next = ((Basechunk29638*) (nxt));
	{
		NI LOC3;
		NIM_BOOL LOC4;
		LOC3 = 0;
		LOC3 = pageindex_31370(next);
		LOC4 = 0;
		LOC4 = contains_30932((&(*a).chunkstarts), LOC3);
		if (!LOC4) goto LA5;
		(*next).prevsize = ((NI) 0);
	}
	LA5: ;
	LOC7 = 0;
	LOC7 = pageindex_31375(p);
	excl_30964((&(*a).chunkstarts), LOC7);
	osdeallocpages_29420(p, size);
	deccurrmem_29816(a, size);
	(*a).freemem -= size;
}

N_NIMCALL(void, freebigchunk_32403)(Memregion29688* a, Bigchunk29642* c_32407) {
	Bigchunk29642* c;
	Basechunk29638* ri;
	c = c_32407;
	(*a).freemem += (*c).Sup.size;
	ri = ((Basechunk29638*) ((NI)((NU64)(((NI) (c))) + (NU64)((*c).Sup.size))));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = isaccessible_32215((&(*a)), ((void*) (ri)));
		if (!(LOC3)) goto LA4;
		LOC3 = chunkunused_31289(ri);
		LA4: ;
		if (!LOC3) goto LA5;
		{
			NIM_BOOL LOC9;
			NI LOC12;
			LOC9 = 0;
			LOC9 = issmallchunk_31269(ri);
			if (!!(LOC9)) goto LA10;
			listremove_33202(&(*a).freechunkslist, ((Bigchunk29642*) (ri)));
			(*c).Sup.size += (*ri).size;
			LOC12 = 0;
			LOC12 = pageindex_31370(ri);
			excl_30964((&(*a).chunkstarts), LOC12);
		}
		LA10: ;
	}
	LA5: ;
	{
		Basechunk29638* le;
		if (!!(((*c).Sup.prevsize == ((NI) 0)))) goto LA15;
		le = ((Basechunk29638*) ((NI)((NU64)(((NI) (c))) - (NU64)((*c).Sup.prevsize))));
		{
			NIM_BOOL LOC19;
			LOC19 = 0;
			LOC19 = isaccessible_32215((&(*a)), ((void*) (le)));
			if (!(LOC19)) goto LA20;
			LOC19 = chunkunused_31289(le);
			LA20: ;
			if (!LOC19) goto LA21;
			{
				NIM_BOOL LOC25;
				Basechunk29638* LOC28;
				NI LOC29;
				LOC25 = 0;
				LOC25 = issmallchunk_31269(le);
				if (!!(LOC25)) goto LA26;
				listremove_33202(&(*a).freechunkslist, ((Bigchunk29642*) (le)));
				(*le).size += (*c).Sup.size;
				LOC28 = 0;
				LOC28 = &c->Sup;
				LOC29 = 0;
				LOC29 = pageindex_31370(LOC28);
				excl_30964((&(*a).chunkstarts), LOC29);
				c = ((Bigchunk29642*) (le));
			}
			LA26: ;
		}
		LA21: ;
	}
	LA15: ;
	{
		NIM_BOOL LOC32;
		Basechunk29638* LOC36;
		NI LOC37;
		LOC32 = 0;
		LOC32 = ((*c).Sup.size < ((NI) 1048576));
		if (LOC32) goto LA33;
		LOC32 = NIM_FALSE;
		LA33: ;
		if (!LOC32) goto LA34;
		LOC36 = 0;
		LOC36 = &c->Sup;
		LOC37 = 0;
		LOC37 = pageindex_31370(LOC36);
		incl_30953(a, (&(*a).chunkstarts), LOC37);
		updateprevsize_32268(a, c, (*c).Sup.size);
		listadd_34423(&(*a).freechunkslist, c);
		(*c).Sup.used = NIM_FALSE;
	}
	goto LA30;
	LA34: ;
	{
		freeoschunks_32007(a, ((void*) (c)), (*c).Sup.size);
	}
	LA30: ;
}

static N_INLINE(void, deallocavlnode_30603)(Memregion29688* a, Avlnode29686* n) {
	(*n).link[(((NI) 0))- 0] = (*a).freeavlnodes;
	(*a).freeavlnodes = n;
}

N_NIMCALL(void, del_30801)(Memregion29688* a, Avlnode29686** t, NI x) {
{	{
		if (!((*t) == bottom_29720)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	(*a).last = (*t);
	{
		if (!((NU64)(x) < (NU64)((*(*t)).key))) goto LA7;
		del_30801(a, &(*(*t)).link[(((NI) 0))- 0], x);
	}
	goto LA5;
	LA7: ;
	{
		(*a).deleted = (*t);
		del_30801(a, &(*(*t)).link[(((NI) 1))- 0], x);
	}
	LA5: ;
	{
		NIM_BOOL LOC12;
		NIM_BOOL LOC13;
		LOC12 = 0;
		LOC13 = 0;
		LOC13 = ((*t) == (*a).last);
		if (!(LOC13)) goto LA14;
		LOC13 = !(((*a).deleted == bottom_29720));
		LA14: ;
		LOC12 = LOC13;
		if (!(LOC12)) goto LA15;
		LOC12 = (x == (*(*a).deleted).key);
		LA15: ;
		if (!LOC12) goto LA16;
		(*(*a).deleted).key = (*(*t)).key;
		(*(*a).deleted).upperbound = (*(*t)).upperbound;
		(*a).deleted = bottom_29720;
		(*t) = (*(*t)).link[(((NI) 1))- 0];
		deallocavlnode_30603(a, (*a).last);
	}
	goto LA10;
	LA16: ;
	{
		NIM_BOOL LOC19;
		LOC19 = 0;
		LOC19 = ((*(*(*t)).link[(((NI) 0))- 0]).level < (NI)((*(*t)).level - ((NI) 1)));
		if (LOC19) goto LA20;
		LOC19 = ((*(*(*t)).link[(((NI) 1))- 0]).level < (NI)((*(*t)).level - ((NI) 1)));
		LA20: ;
		if (!LOC19) goto LA21;
		(*(*t)).level -= ((NI) 1);
		{
			if (!((*(*t)).level < (*(*(*t)).link[(((NI) 1))- 0]).level)) goto LA25;
			(*(*(*t)).link[(((NI) 1))- 0]).level = (*(*t)).level;
		}
		LA25: ;
		skew_30734(t);
		skew_30734(&(*(*t)).link[(((NI) 1))- 0]);
		skew_30734(&(*(*(*t)).link[(((NI) 1))- 0]).link[(((NI) 1))- 0]);
		split_30739(t);
		split_30739(&(*(*t)).link[(((NI) 1))- 0]);
	}
	goto LA10;
	LA21: ;
	LA10: ;
	}BeforeRet: ;
}

N_NIMCALL(void, rawdealloc_43217)(Memregion29688* a, void* p) {
	Basechunk29638* c_43401;
	c_43401 = pageaddr_31380(p);
	{
		NIM_BOOL LOC3;
		Smallchunk29640* c;
		NI s;
		Freecell29630* f;
		LOC3 = 0;
		LOC3 = issmallchunk_31269(c_43401);
		if (!LOC3) goto LA4;
		c = ((Smallchunk29640*) (c_43401));
		s = (*c).Sup.size;
		f = ((Freecell29630*) (p));
		(*f).zerofield = ((NI) 0);
		(*f).next = (*c).freelist;
		(*c).freelist = f;
		{
			if (!((*c).free < s)) goto LA8;
			listadd_37816(&(*a).freesmallchunks[((NI)(s / ((NI) 8)))- 0], c);
			(*c).free += s;
		}
		goto LA6;
		LA8: ;
		{
			(*c).free += s;
			{
				if (!((*c).free == (NI)(((NI) 4096) - (NI)(((NI)sizeof(Smallchunk29640)) - ((NI) 8))))) goto LA13;
				listremove_40602(&(*a).freesmallchunks[((NI)(s / ((NI) 8)))- 0], c);
				(*c).Sup.size = ((NI) 4096);
				freebigchunk_32403(a, ((Bigchunk29642*) (c)));
			}
			LA13: ;
		}
		LA6: ;
	}
	goto LA1;
	LA4: ;
	{
		Bigchunk29642* c;
		c = ((Bigchunk29642*) (c_43401));
		(*a).deleted = bottom_29720;
		del_30801(a, &(*a).root, ((NI) ((&(*c).data))));
		freebigchunk_32403(a, c);
	}
	LA1: ;
}

N_NIMCALL(void, dealloc_46222)(Memregion29688* allocator, void* p) {
	void* x;
	x = ((void*) ((NI)((NU64)(((NI) (p))) - (NU64)(((NI)sizeof(Freecell29630))))));
	rawdealloc_43217(allocator, x);
}

N_NOCONV(void, dealloc_7448)(void* p) {
	dealloc_46222((&gch_49859.region), p);
}

static N_INLINE(void, add_47583)(Cellseq47521* s, Cell47505* c) {
	{
		Cell47505** d;
		void* LOC5;
		if (!((*s).cap <= (*s).len)) goto LA3;
		(*s).cap = (NI)((NI)((*s).cap * ((NI) 3)) / ((NI) 2));
		LOC5 = 0;
		LOC5 = alloc_7401(((NI) ((NI)((*s).cap * ((NI) 8)))));
		d = ((Cell47505**) (LOC5));
		memcpy(((void*) (d)), ((void*) ((*s).d)), ((NI) ((NI)((*s).len * ((NI) 8)))));
		dealloc_7448(((void*) ((*s).d)));
		(*s).d = d;
	}
	LA3: ;
	(*s).d[((*s).len)- 0] = c;
	(*s).len += ((NI) 1);
}

static N_INLINE(void, gcmark_70616)(Gcheap49818* gch, void* p) {
	Cell47505* cell;
	NI c;
	cell = usrtocell_51440(p);
	c = ((NI) (cell));
	{
		Cell47505* objstart;
		void* LOC5;
		if (!((NU64)(((NI) 4096)) < (NU64)(c))) goto LA3;
		LOC5 = 0;
		LOC5 = interiorallocatedptr_44892((&(*gch).region), ((void*) (cell)));
		objstart = ((Cell47505*) (LOC5));
		{
			if (!!((objstart == NIM_NIL))) goto LA8;
			(*objstart).refcount = (NI)((NU64)((*objstart).refcount) + (NU64)(((NI) 8)));
			add_47583((&(*gch).decstack), objstart);
		}
		LA8: ;
	}
	LA3: ;
}

N_CDECL(void, markstackandregisters_72837)(Gcheap49818* gch) {
	jmp_buf registers;
	{
		int LOC3;
		NI max;
		NI sp;
		NI regend;
		LOC3 = 0;
		LOC3 = setjmp(registers);
		if (!(LOC3 == ((NI32) 0))) goto LA4;
		max = ((NI) ((*gch).stackbottom));
		sp = ((NI) ((&registers)));
		regend = (NI)((NU64)(sp) + (NU64)(((NI)sizeof(jmp_buf))));
		{
			while (1) {
				if (!((NU64)(sp) < (NU64)(regend))) goto LA7;
				gcmark_70616(gch, (*((void**) (sp))));
				gcmark_70616(gch, (*((void**) ((NI)((NU64)(sp) + (NU64)(((NI) 4)))))));
				sp = (NI)((NU64)(sp) + (NU64)(((NI) 8)));
			} LA7: ;
		}
		sp = (NI)(sp & ((NI) -8));
		{
			while (1) {
				if (!((NU64)(sp) < (NU64)((NI)(max - ((NI) 64))))) goto LA9;
				gcmark_70616(gch, ((void**) (sp))[(((NI) 0))- 0]);
				gcmark_70616(gch, ((void**) (sp))[(((NI) 1))- 0]);
				gcmark_70616(gch, ((void**) (sp))[(((NI) 2))- 0]);
				gcmark_70616(gch, ((void**) (sp))[(((NI) 3))- 0]);
				gcmark_70616(gch, ((void**) (sp))[(((NI) 4))- 0]);
				gcmark_70616(gch, ((void**) (sp))[(((NI) 5))- 0]);
				gcmark_70616(gch, ((void**) (sp))[(((NI) 6))- 0]);
				gcmark_70616(gch, ((void**) (sp))[(((NI) 7))- 0]);
				sp = (NI)((NU64)(sp) + (NU64)(((NI) 64)));
			} LA9: ;
		}
		{
			while (1) {
				if (!((NU64)(sp) <= (NU64)(max))) goto LA11;
				gcmark_70616(gch, (*((void**) (sp))));
				sp = (NI)((NU64)(sp) + (NU64)(((NI) 8)));
			} LA11: ;
		}
	}
	LA4: ;
}

N_NIMCALL(void, markthreadstacks_71203)(Gcheap49818* gch) {
}

static N_INLINE(NIM_BOOL, canbecycleroot_51458)(Cell47505* c) {
	NIM_BOOL result;
	result = 0;
	result = !((((*(*c).typ).flags &(1U<<((NU)(((NU8) 1))&7U)))!=0));
	return result;
}

static N_INLINE(NI, nexttry_47645)(NI h, NI maxhash) {
	NI result;
	result = 0;
	result = (NI)((NI)((NI)(((NI) 5) * h) + ((NI) 1)) & maxhash);
	return result;
}

N_NIMCALL(Pagedesc47513*, cellsetget_47650)(Cellset47517* t, NI key) {
	Pagedesc47513* result;
	NI h;
{	result = 0;
	h = (NI)(((NI) (key)) & (*t).max);
	{
		while (1) {
			if (!!(((*t).data[(h)- 0] == NIM_NIL))) goto LA2;
			{
				if (!((*(*t).data[(h)- 0]).key == key)) goto LA5;
				result = (*t).data[(h)- 0];
				goto BeforeRet;
			}
			LA5: ;
			h = nexttry_47645(h, (*t).max);
		} LA2: ;
	}
	result = NIM_NIL;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, excl_48274)(Cellset47517* s, Cell47505* cell) {
	NI u;
	Pagedesc47513* t;
	u = ((NI) (cell));
	t = cellsetget_47650((&(*s)), (NI)((NU64)(u) >> (NU64)(((NI) 12))));
	{
		if (!!((t == NIM_NIL))) goto LA3;
		u = (NI)((NU64)((NI)((NU64)(u) % (NU64)(((NI) 4096)))) / (NU64)(((NI) 8)));
		(*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] & (NI)((NU64) ~((NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(u & ((NI) 63)))))))));
	}
	LA3: ;
}

static N_INLINE(void*, celltousr_51422)(Cell47505* cell) {
	void* result;
	result = 0;
	result = ((void*) ((NI)((NU64)(((NI) (cell))) + (NU64)(((NI)sizeof(Cell47505))))));
	return result;
}

N_NIMCALL(void, preparedealloc_52008)(Cell47505* cell) {
	{
		void* LOC5;
		if (!!(((*(*cell).typ).finalizer == NIM_NIL))) goto LA3;
		gch_49859.recgclock += ((NI) 1);
		LOC5 = 0;
		LOC5 = celltousr_51422(cell);
		((Finalizer) ((*(*cell).typ).finalizer))(LOC5);
		gch_49859.recgclock -= ((NI) 1);
	}
	LA3: ;
}

N_NOINLINE(void, addzct_51417)(Cellseq47521* s, Cell47505* c) {
	{
		if (!((NI)((*c).refcount & ((NI) 4)) == ((NI) 0))) goto LA3;
		(*c).refcount = (NI)((*c).refcount | ((NI) 4));
		add_47583(s, c);
	}
	LA3: ;
}

static N_INLINE(void, rtladdzct_53001)(Cell47505* c) {
	addzct_51417((&gch_49859.zct), c);
}

N_NIMCALL(void, cellsetrawinsert_47670)(Cellset47517* t, Pagedesc47513** data, Pagedesc47513* desc) {
	NI h;
	h = (NI)(((NI) ((*desc).key)) & (*t).max);
	{
		while (1) {
			if (!!((data[(h)- 0] == NIM_NIL))) goto LA2;
			h = nexttry_47645(h, (*t).max);
		} LA2: ;
	}
	data[(h)- 0] = desc;
}

N_NIMCALL(void, cellsetenlarge_48003)(Cellset47517* t) {
	NI oldmax;
	Pagedesc47513** n;
	void* LOC1;
	oldmax = (*t).max;
	(*t).max = (NI)((NI)((NI)((*t).max + ((NI) 1)) * ((NI) 2)) - ((NI) 1));
	LOC1 = 0;
	LOC1 = alloc0_7417(((NI) ((NI)((NI)((*t).max + ((NI) 1)) * ((NI) 8)))));
	n = ((Pagedesc47513**) (LOC1));
	{
		NI i_48019;
		NI res_48037;
		i_48019 = 0;
		res_48037 = ((NI) 0);
		{
			while (1) {
				if (!(res_48037 <= oldmax)) goto LA4;
				i_48019 = res_48037;
				{
					if (!!(((*t).data[(i_48019)- 0] == NIM_NIL))) goto LA7;
					cellsetrawinsert_47670((&(*t)), n, (*t).data[(i_48019)- 0]);
				}
				LA7: ;
				res_48037 += ((NI) 1);
			} LA4: ;
		}
	}
	dealloc_7448(((void*) ((*t).data)));
	(*t).data = n;
}

N_NIMCALL(Pagedesc47513*, cellsetput_48041)(Cellset47517* t, NI key) {
	Pagedesc47513* result;
	NI h;
	void* LOC19;
{	result = 0;
	h = (NI)(((NI) (key)) & (*t).max);
	{
		while (1) {
			Pagedesc47513* x;
			x = (*t).data[(h)- 0];
			{
				if (!(x == NIM_NIL)) goto LA5;
				goto LA1;
			}
			LA5: ;
			{
				if (!((*x).key == key)) goto LA9;
				result = x;
				goto BeforeRet;
			}
			LA9: ;
			h = nexttry_47645(h, (*t).max);
		}
	} LA1: ;
	{
		NIM_BOOL LOC13;
		LOC13 = 0;
		LOC13 = ((NI)((NI)((*t).max + ((NI) 1)) * ((NI) 2)) < (NI)((*t).counter * ((NI) 3)));
		if (LOC13) goto LA14;
		LOC13 = ((NI)((NI)((*t).max + ((NI) 1)) - (*t).counter) < ((NI) 4));
		LA14: ;
		if (!LOC13) goto LA15;
		cellsetenlarge_48003(t);
	}
	LA15: ;
	(*t).counter += ((NI) 1);
	h = (NI)(((NI) (key)) & (*t).max);
	{
		while (1) {
			if (!!(((*t).data[(h)- 0] == NIM_NIL))) goto LA18;
			h = nexttry_47645(h, (*t).max);
		} LA18: ;
	}
	LOC19 = 0;
	LOC19 = alloc0_7417(((NI) (((NI)sizeof(Pagedesc47513)))));
	result = ((Pagedesc47513*) (LOC19));
	(*result).next = (*t).head;
	(*result).key = key;
	(*t).head = result;
	(*t).data[(h)- 0] = result;
	}BeforeRet: ;
	return result;
}

N_NOINLINE(void, incl_48247)(Cellset47517* s, Cell47505* cell) {
	NI u;
	Pagedesc47513* t;
	u = ((NI) (cell));
	t = cellsetput_48041(s, (NI)((NU64)(u) >> (NU64)(((NI) 12))));
	u = (NI)((NU64)((NI)((NU64)(u) % (NU64)(((NI) 4096)))) / (NU64)(((NI) 8)));
	(*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] = (NI)((*t).bits[((NI)((NU64)(u) >> (NU64)(((NI) 6))))- 0] | (NI)((NU64)(((NI) 1)) << (NU64)(((NI) ((NI)(u & ((NI) 63)))))));
}

static N_INLINE(void, rtladdcycleroot_52220)(Cell47505* c) {
	{
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		incl_48247((&gch_49859.cycleroots), c);
	}
	LA3: ;
}

static N_INLINE(void, decref_53401)(Cell47505* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_53001(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		LOC6 = 0;
		LOC6 = canbecycleroot_51458(c);
		if (!LOC6) goto LA7;
		rtladdcycleroot_52220(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
}

N_NIMCALL(void, markgray_67002)(Cell47505* s) {
	{
		if (!!((((NI) ((NI)((*s).refcount & ((NI) 3)))) == ((NI) 1)))) goto LA3;
		(*s).refcount = (NI)((NI)((*s).refcount & ((NI) -4)) | ((NI) 1));
		forallchildren_51814(s, ((NU8) 5));
	}
	LA3: ;
}

N_NIMCALL(void, scanblack_67201)(Cell47505* s) {
	(*s).refcount = (NI)((*s).refcount & ((NI) -4));
	forallchildren_51814(s, ((NU8) 7));
}

N_NIMCALL(void, scan_67401)(Cell47505* s) {
	{
		if (!(((NI) ((NI)((*s).refcount & ((NI) 3)))) == ((NI) 1))) goto LA3;
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*s).refcount))) goto LA7;
			scanblack_67201(s);
		}
		goto LA5;
		LA7: ;
		{
			(*s).refcount = (NI)((NI)((*s).refcount & ((NI) -4)) | ((NI) 2));
			forallchildren_51814(s, ((NU8) 6));
		}
		LA5: ;
	}
	LA3: ;
}

N_NIMCALL(NIM_BOOL, isallocatedptr_36602)(Memregion29688* a, void* p) {
	NIM_BOOL result;
	result = 0;
	{
		NIM_BOOL LOC3;
		Basechunk29638* c_44813;
		LOC3 = 0;
		LOC3 = isaccessible_32215(a, p);
		if (!LOC3) goto LA4;
		c_44813 = pageaddr_31380(p);
		{
			NIM_BOOL LOC8;
			LOC8 = 0;
			LOC8 = chunkunused_31289(c_44813);
			if (!!(LOC8)) goto LA9;
			{
				NIM_BOOL LOC13;
				Smallchunk29640* c;
				NI offset;
				NIM_BOOL LOC16;
				NIM_BOOL LOC17;
				LOC13 = 0;
				LOC13 = issmallchunk_31269(c_44813);
				if (!LOC13) goto LA14;
				c = ((Smallchunk29640*) (c_44813));
				offset = (NI)((NU64)(((NI) ((NI)(((NI) (p)) & ((NI) 4095))))) - (NU64)((NI)(((NI)sizeof(Smallchunk29640)) - ((NI) 8))));
				LOC16 = 0;
				LOC17 = 0;
				LOC17 = ((NU64)(offset) < (NU64)((*c).acc));
				if (!(LOC17)) goto LA18;
				LOC17 = ((NI)((NU64)(offset) % (NU64)((*c).Sup.size)) == ((NI) 0));
				LA18: ;
				LOC16 = LOC17;
				if (!(LOC16)) goto LA19;
				LOC16 = ((NU64)(((NI) 1)) < (NU64)((*((Freecell29630*) (p))).zerofield));
				LA19: ;
				result = LOC16;
			}
			goto LA11;
			LA14: ;
			{
				Bigchunk29642* c;
				NIM_BOOL LOC21;
				c = ((Bigchunk29642*) (c_44813));
				LOC21 = 0;
				LOC21 = (p == ((void*) ((&(*c).data))));
				if (!(LOC21)) goto LA22;
				LOC21 = ((NU64)(((NI) 1)) < (NU64)((*((Freecell29630*) (p))).zerofield));
				LA22: ;
				result = LOC21;
			}
			LA11: ;
		}
		LA9: ;
	}
	LA4: ;
	return result;
}

N_NIMCALL(void, freecycliccell_66215)(Gcheap49818* gch, Cell47505* c) {
	preparedealloc_52008(c);
	rawdealloc_43217((&(*gch).region), ((void*) (c)));
}

N_NIMCALL(void, collectwhite_67601)(Cell47505* s) {
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = isallocatedptr_36602((&gch_49859.region), ((void*) (s)));
		if (!(LOC3)) goto LA4;
		LOC3 = (((NI) ((NI)((*s).refcount & ((NI) 3)))) == ((NI) 2));
		LA4: ;
		if (!LOC3) goto LA5;
		(*s).refcount = (NI)((*s).refcount & ((NI) -4));
		forallchildren_51814(s, ((NU8) 8));
		freecycliccell_66215((&gch_49859), s);
	}
	LA5: ;
}

N_NIMCALL(void, dooperation_51818)(void* p, NU8 op) {
	Cell47505* c;
{	{
		if (!(p == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	c = usrtocell_51440(p);
	switch (op) {
	case ((NU8) 2):
	{
		decref_53401(c);
	}
	break;
	case ((NU8) 3):
	{
		add_47583((&gch_49859.tempstack), c);
	}
	break;
	case ((NU8) 4):
	{
		(*c).refcount = (NI)((NU64)((*c).refcount) - (NU64)(((NI) 8)));
	}
	break;
	case ((NU8) 5):
	{
		(*c).refcount = (NI)((NU64)((*c).refcount) - (NU64)(((NI) 8)));
		markgray_67002(c);
	}
	break;
	case ((NU8) 6):
	{
		scan_67401(c);
	}
	break;
	case ((NU8) 7):
	{
		(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
		{
			if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 0)))) goto LA13;
			scanblack_67201(c);
		}
		LA13: ;
	}
	break;
	case ((NU8) 8):
	{
		collectwhite_67601(c);
	}
	break;
	case ((NU8) 0):
	{
	}
	break;
	case ((NU8) 1):
	{
	}
	break;
	}
	}BeforeRet: ;
}

N_NIMCALL(NI, getdiscriminant_27204)(void* aa, TNimNode* n) {
	NI result;
	NI d;
	NI a;
{	result = 0;
	d = 0;
	a = ((NI) (aa));
	switch ((*(*n).typ).size) {
	case ((NI) 1):
	{
		d = ((NI)(NU)(NU8)((*((NI8*) ((NI)((NU64)(a) + (NU64)((*n).offset)))))));
	}
	break;
	case ((NI) 2):
	{
		d = ((NI)(NU)(NU16)((*((NI16*) ((NI)((NU64)(a) + (NU64)((*n).offset)))))));
	}
	break;
	case ((NI) 4):
	{
		d = ((NI) ((*((NI32*) ((NI)((NU64)(a) + (NU64)((*n).offset)))))));
	}
	break;
	default:
	{
	}
	break;
	}
	result = d;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(TNimNode*, selectbranch_27607)(void* aa, TNimNode* n) {
	TNimNode* result;
	NI discr;
	result = 0;
	discr = getdiscriminant_27204(aa, n);
	{
		if (!((NU64)(discr) < (NU64)((*n).len))) goto LA3;
		result = (*n).sons[(discr)- 0];
		{
			if (!(result == NIM_NIL)) goto LA7;
			result = (*n).sons[((*n).len)- 0];
		}
		LA7: ;
	}
	goto LA1;
	LA3: ;
	{
		result = (*n).sons[((*n).len)- 0];
	}
	LA1: ;
	return result;
}

N_NIMCALL(void, forallslotsaux_56005)(void* dest, TNimNode* n, NU8 op) {
	NI d;
	d = ((NI) (dest));
	switch ((*n).kind) {
	case ((NU8) 1):
	{
		forallchildrenaux_51822(((void*) ((NI)((NU64)(d) + (NU64)((*n).offset)))), (*n).typ, op);
	}
	break;
	case ((NU8) 2):
	{
		{
			NI i_56030;
			NI HEX3Atmp_56206;
			NI res_56209;
			i_56030 = 0;
			HEX3Atmp_56206 = 0;
			HEX3Atmp_56206 = (NI)((*n).len - ((NI) 1));
			res_56209 = ((NI) 0);
			{
				while (1) {
					if (!(res_56209 <= HEX3Atmp_56206)) goto LA5;
					i_56030 = res_56209;
					{
						if (!((*(*n).sons[(i_56030)- 0]).kind == ((NU8) 1))) goto LA8;
						{
							if (!((289406976 &((NU64)1<<((NU)((*(*(*n).sons[(i_56030)- 0]).typ).kind)&63U)))!=0)) goto LA12;
							dooperation_51818((*((void**) ((NI)((NU64)(d) + (NU64)((*(*n).sons[(i_56030)- 0]).offset))))), op);
						}
						goto LA10;
						LA12: ;
						{
							forallchildrenaux_51822(((void*) ((NI)((NU64)(d) + (NU64)((*(*n).sons[(i_56030)- 0]).offset)))), (*(*n).sons[(i_56030)- 0]).typ, op);
						}
						LA10: ;
					}
					goto LA6;
					LA8: ;
					{
						forallslotsaux_56005(dest, (*n).sons[(i_56030)- 0], op);
					}
					LA6: ;
					res_56209 += ((NI) 1);
				} LA5: ;
			}
		}
	}
	break;
	case ((NU8) 3):
	{
		TNimNode* m;
		m = selectbranch_27607(dest, n);
		{
			if (!!((m == NIM_NIL))) goto LA19;
			forallslotsaux_56005(dest, m, op);
		}
		LA19: ;
	}
	break;
	case ((NU8) 0):
	{
	}
	break;
	}
}

N_NIMCALL(void, forallchildrenaux_51822)(void* dest, TNimType* mt, NU8 op) {
	NI d;
{	d = ((NI) (dest));
	{
		if (!(dest == NIM_NIL)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!!((((*mt).flags &(1U<<((NU)(((NU8) 0))&7U)))!=0))) goto LA7;
		switch ((*mt).kind) {
		case ((NU8) 22):
		case ((NU8) 28):
		case ((NU8) 24):
		{
			dooperation_51818((*((void**) (d))), op);
		}
		break;
		case ((NU8) 17):
		case ((NU8) 18):
		{
			forallslotsaux_56005(dest, (*mt).node, op);
		}
		break;
		case ((NU8) 16):
		case ((NU8) 4):
		case ((NU8) 27):
		{
			{
				NI i_56238;
				NI HEX3Atmp_56261;
				NI res_56264;
				i_56238 = 0;
				HEX3Atmp_56261 = 0;
				HEX3Atmp_56261 = (NI)((NI)((*mt).size / (*(*mt).base).size) - ((NI) 1));
				res_56264 = ((NI) 0);
				{
					while (1) {
						if (!(res_56264 <= HEX3Atmp_56261)) goto LA14;
						i_56238 = res_56264;
						forallchildrenaux_51822(((void*) ((NI)((NU64)(d) + (NU64)((NI)((NU64)(i_56238) * (NU64)((*(*mt).base).size)))))), (*mt).base, op);
						res_56264 += ((NI) 1);
					} LA14: ;
				}
			}
		}
		break;
		default:
		{
		}
		break;
		}
	}
	LA7: ;
	}BeforeRet: ;
}

N_NIMCALL(void, forallchildren_51814)(Cell47505* cell, NU8 op) {
	TY3489 marker;
	marker = (*(*cell).typ).marker;
	{
		void* LOC5;
		if (!!((marker == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = celltousr_51422(cell);
		marker(LOC5, ((NI) (op)));
	}
	goto LA1;
	LA3: ;
	{
		switch ((*(*cell).typ).kind) {
		case ((NU8) 22):
		{
			void* LOC8;
			LOC8 = 0;
			LOC8 = celltousr_51422(cell);
			forallchildrenaux_51822(LOC8, (*(*cell).typ).base, op);
		}
		break;
		case ((NU8) 24):
		{
			NI d;
			void* LOC10;
			TGenericSeq* s;
			LOC10 = 0;
			LOC10 = celltousr_51422(cell);
			d = ((NI) (LOC10));
			s = ((TGenericSeq*) (d));
			{
				if (!!((s == NIM_NIL))) goto LA13;
				{
					NI i_57034;
					NI HEX3Atmp_57067;
					NI res_57070;
					i_57034 = 0;
					HEX3Atmp_57067 = 0;
					HEX3Atmp_57067 = (NI)((*s).len - ((NI) 1));
					res_57070 = ((NI) 0);
					{
						while (1) {
							if (!(res_57070 <= HEX3Atmp_57067)) goto LA17;
							i_57034 = res_57070;
							forallchildrenaux_51822(((void*) ((NI)((NU64)((NI)((NU64)(d) + (NU64)((NI)((NU64)(i_57034) * (NU64)((*(*(*cell).typ).base).size))))) + (NU64)(((NI) 16))))), (*(*cell).typ).base, op);
							res_57070 += ((NI) 1);
						} LA17: ;
					}
				}
			}
			LA13: ;
		}
		break;
		default:
		{
		}
		break;
		}
	}
	LA1: ;
}

N_NIMCALL(NIM_BOOL, collectzct_70006)(Gcheap49818* gch) {
	NIM_BOOL result;
	NI* L;
	result = 0;
	L = (&(*gch).zct.len);
	{
		while (1) {
			Cell47505* c;
			if (!(((NI) 0) < (*L))) goto LA2;
			c = (*gch).zct.d[(((NI) 0))- 0];
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			(*gch).zct.d[(((NI) 0))- 0] = (*gch).zct.d[((NI)((*L) - ((NI) 1)))- 0];
			(*L) -= ((NI) 1);
			{
				if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA5;
				{
					NIM_BOOL LOC9;
					LOC9 = 0;
					LOC9 = canbecycleroot_51458(c);
					if (!LOC9) goto LA10;
					excl_48274((&(*gch).cycleroots), c);
				}
				LA10: ;
				preparedealloc_52008(c);
				forallchildren_51814(c, ((NU8) 2));
				rawdealloc_43217((&(*gch).region), ((void*) (c)));
			}
			LA5: ;
		} LA2: ;
	}
	result = NIM_TRUE;
	return result;
}

N_NIMCALL(void, markroots_67802)(Gcheap49818* gch) {
	NI tabsize;
	tabsize = ((NI) 0);
	{
		Cell47505* s_67807;
		Cellset47517 HEX3Atmp_67834;
		Pagedesc47513* r_67839;
		s_67807 = 0;
		memset((void*)(&HEX3Atmp_67834), 0, sizeof(HEX3Atmp_67834));
		HEX3Atmp_67834 = (*gch).cycleroots;
		r_67839 = HEX3Atmp_67834.head;
		{
			while (1) {
				NI i_67841;
				if (!!((r_67839 == NIM_NIL))) goto LA3;
				i_67841 = ((NI) 0);
				{
					while (1) {
						NI w_67843;
						NI j_67845;
						if (!(i_67841 <= ((NI) 7))) goto LA5;
						w_67843 = (*r_67839).bits[(i_67841)- 0];
						j_67845 = ((NI) 0);
						{
							while (1) {
								if (!!((w_67843 == ((NI) 0)))) goto LA7;
								{
									if (!!((((NI) ((NI)(w_67843 & ((NI) 1)))) == ((NI) 0)))) goto LA10;
									s_67807 = ((Cell47505*) ((NI)((NI)((NU64)((*r_67839).key) << (NU64)(((NI) 12))) | (NI)((NU64)((NI)((NU64)((NI)((NU64)(i_67841) << (NU64)(((NI) 6)))) + (NU64)(j_67845))) * (NU64)(((NI) 8))))));
									tabsize += ((NI) 1);
									{
										NIM_BOOL LOC14;
										LOC14 = 0;
										LOC14 = (((NI) ((NI)((*s_67807).refcount & ((NI) 3)))) == ((NI) 3));
										if (!(LOC14)) goto LA15;
										LOC14 = ((NU64)(((NI) 8)) <= (NU64)((*s_67807).refcount));
										LA15: ;
										if (!LOC14) goto LA16;
										markgray_67002(s_67807);
									}
									goto LA12;
									LA16: ;
									{
										excl_48274((&(*gch).cycleroots), s_67807);
										{
											if (!((*s_67807).refcount == ((NI) 0))) goto LA21;
											freecycliccell_66215(gch, s_67807);
										}
										LA21: ;
									}
									LA12: ;
								}
								LA10: ;
								j_67845 += ((NI) 1);
								w_67843 = (NI)((NU64)(w_67843) >> (NU64)(((NI) 1)));
							} LA7: ;
						}
						i_67841 += ((NI) 1);
					} LA5: ;
				}
				r_67839 = (*r_67839).next;
			} LA3: ;
		}
	}
	(*gch).stat.cycletablesize = (((*gch).stat.cycletablesize >= tabsize) ? (*gch).stat.cycletablesize : tabsize);
}

N_NIMCALL(void, collectroots_70201)(Gcheap49818* gch) {
	{
		Cell47505* s_70205;
		Cellset47517 HEX3Atmp_70207;
		Pagedesc47513* r_70212;
		s_70205 = 0;
		memset((void*)(&HEX3Atmp_70207), 0, sizeof(HEX3Atmp_70207));
		HEX3Atmp_70207 = (*gch).cycleroots;
		r_70212 = HEX3Atmp_70207.head;
		{
			while (1) {
				NI i_70214;
				if (!!((r_70212 == NIM_NIL))) goto LA3;
				i_70214 = ((NI) 0);
				{
					while (1) {
						NI w_70216;
						NI j_70218;
						if (!(i_70214 <= ((NI) 7))) goto LA5;
						w_70216 = (*r_70212).bits[(i_70214)- 0];
						j_70218 = ((NI) 0);
						{
							while (1) {
								if (!!((w_70216 == ((NI) 0)))) goto LA7;
								{
									if (!!((((NI) ((NI)(w_70216 & ((NI) 1)))) == ((NI) 0)))) goto LA10;
									s_70205 = ((Cell47505*) ((NI)((NI)((NU64)((*r_70212).key) << (NU64)(((NI) 12))) | (NI)((NU64)((NI)((NU64)((NI)((NU64)(i_70214) << (NU64)(((NI) 6)))) + (NU64)(j_70218))) * (NU64)(((NI) 8))))));
									collectwhite_67601(s_70205);
								}
								LA10: ;
								j_70218 += ((NI) 1);
								w_70216 = (NI)((NU64)(w_70216) >> (NU64)(((NI) 1)));
							} LA7: ;
						}
						i_70214 += ((NI) 1);
					} LA5: ;
				}
				r_70212 = (*r_70212).next;
			} LA3: ;
		}
	}
}

N_NIMCALL(void, deinit_47626)(Cellset47517* s) {
	Pagedesc47513* it;
	it = (*s).head;
	{
		while (1) {
			Pagedesc47513* n;
			if (!!((it == NIM_NIL))) goto LA2;
			n = (*it).next;
			dealloc_7448(((void*) (it)));
			it = n;
		} LA2: ;
	}
	(*s).head = NIM_NIL;
	dealloc_7448(((void*) ((*s).data)));
	(*s).data = NIM_NIL;
	(*s).counter = ((NI) 0);
}

N_NIMCALL(void, cellsetreset_56001)(Cellset47517* s) {
	deinit_47626(s);
	init_47618(s);
}

N_NIMCALL(void, collectcycles_70220)(Gcheap49818* gch) {
	{
		while (1) {
			NIM_BOOL LOC3;
			if (!(((NI) 0) < (*gch).zct.len)) goto LA2;
			LOC3 = 0;
			LOC3 = collectzct_70006(gch);
		} LA2: ;
	}
	markroots_67802(gch);
	{
		Cell47505* s_70401;
		Cellset47517 HEX3Atmp_70603;
		Pagedesc47513* r_70608;
		s_70401 = 0;
		memset((void*)(&HEX3Atmp_70603), 0, sizeof(HEX3Atmp_70603));
		HEX3Atmp_70603 = (*gch).cycleroots;
		r_70608 = HEX3Atmp_70603.head;
		{
			while (1) {
				NI i_70610;
				if (!!((r_70608 == NIM_NIL))) goto LA6;
				i_70610 = ((NI) 0);
				{
					while (1) {
						NI w_70612;
						NI j_70614;
						if (!(i_70610 <= ((NI) 7))) goto LA8;
						w_70612 = (*r_70608).bits[(i_70610)- 0];
						j_70614 = ((NI) 0);
						{
							while (1) {
								if (!!((w_70612 == ((NI) 0)))) goto LA10;
								{
									if (!!((((NI) ((NI)(w_70612 & ((NI) 1)))) == ((NI) 0)))) goto LA13;
									s_70401 = ((Cell47505*) ((NI)((NI)((NU64)((*r_70608).key) << (NU64)(((NI) 12))) | (NI)((NU64)((NI)((NU64)((NI)((NU64)(i_70610) << (NU64)(((NI) 6)))) + (NU64)(j_70614))) * (NU64)(((NI) 8))))));
									scan_67401(s_70401);
								}
								LA13: ;
								j_70614 += ((NI) 1);
								w_70612 = (NI)((NU64)(w_70612) >> (NU64)(((NI) 1)));
							} LA10: ;
						}
						i_70610 += ((NI) 1);
					} LA8: ;
				}
				r_70608 = (*r_70608).next;
			} LA6: ;
		}
	}
	collectroots_70201(gch);
	cellsetreset_56001((&(*gch).cycleroots));
}

N_NIMCALL(NI, gettotalmem_8059)(void) {
	NI result;
{	result = 0;
	result = gch_49859.region.currmem;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, getfreemem_8057)(void) {
	NI result;
	result = 0;
	result = gch_49859.region.freemem;
	return result;
}

N_NIMCALL(NI, getoccupiedmem_8055)(void) {
	NI result;
	NI LOC1;
	NI LOC2;
{	result = 0;
	LOC1 = 0;
	LOC1 = gettotalmem_8059();
	LOC2 = 0;
	LOC2 = getfreemem_8057();
	result = (NI)(LOC1 - LOC2);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, unmarkstackandregisters_75202)(Gcheap49818* gch) {
	Cell47505** d;
	d = (*gch).decstack.d;
	{
		NI i_75216;
		NI HEX3Atmp_75402;
		NI res_75405;
		i_75216 = 0;
		HEX3Atmp_75402 = 0;
		HEX3Atmp_75402 = (NI)((*gch).decstack.len - ((NI) 1));
		res_75405 = ((NI) 0);
		{
			while (1) {
				if (!(res_75405 <= HEX3Atmp_75402)) goto LA3;
				i_75216 = res_75405;
				decref_53401(d[(i_75216)- 0]);
				res_75405 += ((NI) 1);
			} LA3: ;
		}
	}
	(*gch).decstack.len = ((NI) 0);
}

N_NIMCALL(void, collectctbody_75409)(Gcheap49818* gch) {
	NI LOC1;
	LOC1 = 0;
	LOC1 = stacksize_71601();
	(*gch).stat.maxstacksize = (((*gch).stat.maxstacksize >= LOC1) ? (*gch).stat.maxstacksize : LOC1);
	prepareforinteriorpointerchecking_44888((&(*gch).region));
	markstackandregisters_72837(gch);
	markthreadstacks_71203(gch);
	(*gch).stat.maxstackcells = (((*gch).stat.maxstackcells >= (*gch).decstack.len) ? (*gch).stat.maxstackcells : (*gch).decstack.len);
	(*gch).stat.stackscans += ((NI) 1);
	{
		NIM_BOOL LOC4;
		LOC4 = 0;
		LOC4 = collectzct_70006(gch);
		if (!LOC4) goto LA5;
		{
			NIM_BOOL LOC9;
			NI LOC10;
			NI LOC14;
			LOC9 = 0;
			LOC10 = 0;
			LOC10 = getoccupiedmem_47430((&(*gch).region));
			LOC9 = ((*gch).cyclethreshold <= LOC10);
			if (LOC9) goto LA11;
			LOC9 = NIM_FALSE;
			LA11: ;
			if (!LOC9) goto LA12;
			collectcycles_70220(gch);
			(*gch).stat.cyclecollections += ((NI) 1);
			LOC14 = 0;
			LOC14 = getoccupiedmem_8055();
			(*gch).cyclethreshold = ((((NI) 4194304) >= (NI)(LOC14 * ((NI) 2))) ? ((NI) 4194304) : (NI)(LOC14 * ((NI) 2)));
			(*gch).stat.maxthreshold = (((*gch).stat.maxthreshold >= (*gch).cyclethreshold) ? (*gch).stat.maxthreshold : (*gch).cyclethreshold);
		}
		LA12: ;
	}
	LA5: ;
	unmarkstackandregisters_75202(gch);
}

N_NIMCALL(void, collectct_51807)(Gcheap49818* gch) {
	NI stackmarkcosts;
	NI LOC1;
	LOC1 = 0;
	LOC1 = stacksize_71601();
	stackmarkcosts = (((NI)(LOC1 / ((NI) 128)) >= ((NI) 500)) ? (NI)(LOC1 / ((NI) 128)) : ((NI) 500));
	{
		NIM_BOOL LOC4;
		NIM_BOOL LOC5;
		NIM_BOOL LOC6;
		NIM_BOOL LOC8;
		NI LOC10;
		LOC4 = 0;
		LOC5 = 0;
		LOC6 = 0;
		LOC6 = (stackmarkcosts <= (*gch).zct.len);
		if (LOC6) goto LA7;
		LOC8 = 0;
		LOC8 = NIM_TRUE;
		if (!(LOC8)) goto LA9;
		LOC10 = 0;
		LOC10 = getoccupiedmem_47430((&(*gch).region));
		LOC8 = ((*gch).cyclethreshold <= LOC10);
		LA9: ;
		LOC6 = LOC8;
		LA7: ;
		LOC5 = LOC6;
		if (LOC5) goto LA11;
		LOC5 = NIM_FALSE;
		LA11: ;
		LOC4 = LOC5;
		if (!(LOC4)) goto LA12;
		LOC4 = ((*gch).recgclock == ((NI) 0));
		LA12: ;
		if (!LOC4) goto LA13;
		collectctbody_75409(gch);
	}
	LA13: ;
}

static N_INLINE(void, addnewobjtozct_57074)(Cell47505* res, Gcheap49818* gch) {
	NI L;
	Cell47505** d;
{	L = (*gch).zct.len;
	d = (*gch).zct.d;
	{
		Cell47505* c;
		if (!(((NI) 8) < L)) goto LA3;
		c = 0;
		c = d[((NI)(L - ((NI) 1)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA7;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 1)))- 0] = res;
			goto BeforeRet;
		}
		LA7: ;
		c = d[((NI)(L - ((NI) 2)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA11;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 2)))- 0] = res;
			goto BeforeRet;
		}
		LA11: ;
		c = d[((NI)(L - ((NI) 3)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA15;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 3)))- 0] = res;
			goto BeforeRet;
		}
		LA15: ;
		c = d[((NI)(L - ((NI) 4)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA19;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 4)))- 0] = res;
			goto BeforeRet;
		}
		LA19: ;
		c = d[((NI)(L - ((NI) 5)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA23;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 5)))- 0] = res;
			goto BeforeRet;
		}
		LA23: ;
		c = d[((NI)(L - ((NI) 6)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA27;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 6)))- 0] = res;
			goto BeforeRet;
		}
		LA27: ;
		c = d[((NI)(L - ((NI) 7)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA31;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 7)))- 0] = res;
			goto BeforeRet;
		}
		LA31: ;
		c = d[((NI)(L - ((NI) 8)))- 0];
		{
			if (!((NU64)(((NI) 8)) <= (NU64)((*c).refcount))) goto LA35;
			(*c).refcount = (NI)((*c).refcount & ((NI) -5));
			d[((NI)(L - ((NI) 8)))- 0] = res;
			goto BeforeRet;
		}
		LA35: ;
		add_47583((&(*gch).zct), res);
	}
	goto LA1;
	LA3: ;
	{
		d[(L)- 0] = res;
		(*gch).zct.len += ((NI) 1);
	}
	LA1: ;
	}BeforeRet: ;
}

N_NIMCALL(void*, rawnewobj_57601)(TNimType* typ, NI size, Gcheap49818* gch) {
	void* result;
	Cell47505* res;
	void* LOC1;
	result = 0;
	collectct_51807(gch);
	LOC1 = 0;
	LOC1 = rawalloc_36868((&(*gch).region), (NI)(size + ((NI)sizeof(Cell47505))));
	res = ((Cell47505*) (LOC1));
	(*res).typ = typ;
	(*res).refcount = ((NI) 4);
	addnewobjtozct_57074(res, gch);
	result = celltousr_51422(res);
	return result;
}

N_NIMCALL(void*, newObjNoInit)(TNimType* typ, NI size) {
	void* result;
	result = 0;
	result = rawnewobj_57601(typ, size, (&gch_49859));
	return result;
}

N_NIMCALL(NimStringDesc*, rawNewStringNoInit)(NI space) {
	NimStringDesc* result;
	NI s;
	void* LOC5;
	result = 0;
	s = space;
	{
		if (!(s < ((NI) 7))) goto LA3;
		s = ((NI) 7);
	}
	LA3: ;
	LOC5 = 0;
	LOC5 = newObjNoInit((&strdesc_12203), (NI)((NI)(((NI)sizeof(TGenericSeq)) + s) + ((NI) 1)));
	result = ((NimStringDesc*) (LOC5));
	(*result).Sup.reserved = s;
	return result;
}

N_NIMCALL(NimStringDesc*, toNimStr)(NCSTRING str, NI len) {
	NimStringDesc* result;
	result = 0;
	result = rawNewStringNoInit(len);
	(*result).Sup.len = len;
	memcpy(((NCSTRING) ((*result).data)), str, (NI)(len + ((NI) 1)));
	return result;
}

N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str) {
	NimStringDesc* result;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = strlen(str);
	result = toNimStr(str, LOC1);
	return result;
}

N_NIMCALL(void, write_15501)(FILE* f, NCSTRING c) {
	fputs(c, f);
}

N_NIMCALL(void, writetostderr_19401)(NCSTRING msg) {
	write_15501(stderr, msg);
}

N_NIMCALL(void, showerrormessage_19406)(NCSTRING data) {
	{
		NimStringDesc* LOC5;
		if (!!((errormessagewriter_19204 == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = cstrToNimstr(data);
		errormessagewriter_19204(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		writetostderr_19401(data);
	}
	LA1: ;
}

N_NOCONV(void, signalHandler)(int sig) {
	NCSTRING msg;
	msg = 0;
	{
		if (!(sig == SIGINT)) goto LA3;
		msg = "SIGINT: Interrupted by Ctrl-C.\012";
	}
	goto LA1;
	LA3: ;
	{
		if (!(sig == SIGSEGV)) goto LA6;
		msg = "SIGSEGV: Illegal storage access. (Attempt to read from nil?)\012";
	}
	goto LA1;
	LA6: ;
	{
		if (!(sig == SIGABRT)) goto LA9;
		msg = "SIGABRT: Abnormal termination.\012";
	}
	goto LA1;
	LA9: ;
	{
		if (!(sig == SIGFPE)) goto LA12;
		msg = "SIGFPE: Arithmetic error.\012";
	}
	goto LA1;
	LA12: ;
	{
		if (!(sig == SIGILL)) goto LA15;
		msg = "SIGILL: Illegal operation.\012";
	}
	goto LA1;
	LA15: ;
	{
		if (!(sig == SIGSEGV)) goto LA18;
		msg = "SIGBUS: Illegal storage access. (Attempt to read from nil?)\012";
	}
	goto LA1;
	LA18: ;
	{
		{
			{
				if (!(sig == SIGPIPE)) goto LA24;
				msg = "SIGPIPE: Pipe closed.\012";
				goto LA21;
			}
			LA24: ;
			msg = "unknown signal\012";
		} LA21: ;
	}
	LA1: ;
	showerrormessage_19406(msg);
	exit(((NI) 1));
}

N_NIMCALL(void, registersignalhandler_23002)(void) {
	signal(SIGINT, signalHandler);
	signal(SIGSEGV, signalHandler);
	signal(SIGABRT, signalHandler);
	signal(SIGFPE, signalHandler);
	signal(SIGILL, signalHandler);
	signal(SIGSEGV, signalHandler);
	signal(SIGPIPE, signalHandler);
}

N_NIMCALL(NI, getRefcount)(void* p) {
	NI result;
	Cell47505* LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = usrtocell_51440(p);
	result = (NI)((NU64)((*LOC1).refcount) >> (NU64)(((NI) 3)));
	return result;
}

N_NIMCALL(NIM_BOOL, open_15403)(FILE** f, NimStringDesc* filename, NU8 mode, NI bufsize) {
	NIM_BOOL result;
	void* p;
	result = 0;
	p = fopen(filename->data, Formatopen_82610[(mode)- 0]->data);
	{
		if (!!((p == NIM_NIL))) goto LA3;
		result = NIM_TRUE;
		(*f) = ((FILE*) (p));
		{
			NIM_BOOL LOC7;
			int LOC11;
			LOC7 = 0;
			LOC7 = (((NI) 0) < bufsize);
			if (!(LOC7)) goto LA8;
			LOC7 = (bufsize <= ((NI) 2147483647));
			LA8: ;
			if (!LOC7) goto LA9;
			LOC11 = 0;
			LOC11 = setvbuf((*f), NIM_NIL, _IOFBF, ((int) (bufsize)));
		}
		goto LA5;
		LA9: ;
		{
			int LOC15;
			if (!(bufsize == ((NI) 0))) goto LA13;
			LOC15 = 0;
			LOC15 = setvbuf((*f), NIM_NIL, _IONBF, ((int) 0));
		}
		goto LA5;
		LA13: ;
		LA5: ;
	}
	LA3: ;
	return result;
}

N_NIMCALL(void, nimGCvisit)(void* d, NI op) {
	dooperation_51818(d, ((NU8) (op)));
}
N_NIMCALL(void, TMP24)(void* p, NI op) {
	Exception* a;
	a = (Exception*)p;
	nimGCvisit((void*)(*a).parent, op);
	nimGCvisit((void*)(*a).message, op);
	nimGCvisit((void*)(*a).trace, op);
}
N_NIMCALL(void, TMP25)(void* p, NI op) {
	Ioerror3628* a;
	a = (Ioerror3628*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
}

N_NIMCALL(void*, newObj)(TNimType* typ, NI size) {
	void* result;
	result = 0;
	result = rawnewobj_57601(typ, size, (&gch_49859));
	zeroMem(result, ((NI) (size)));
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, rawNewString)(NI space) {
	NimStringDesc* result;
	NI s;
	void* LOC5;
	result = 0;
	s = space;
	{
		if (!(s < ((NI) 7))) goto LA3;
		s = ((NI) 7);
	}
	LA3: ;
	LOC5 = 0;
	LOC5 = newObj((&strdesc_12203), (NI)((NI)(((NI)sizeof(TGenericSeq)) + s) + ((NI) 1)));
	result = ((NimStringDesc*) (LOC5));
	(*result).Sup.reserved = s;
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		Cell47505* c;
		if (!!((src == NIM_NIL))) goto LA3;
		c = usrtocell_51440(src);
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	{
		Cell47505* c;
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		c = usrtocell_51440((*dest));
		{
			(*c).refcount -= ((NI) 8);
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			rtladdzct_53001(c);
		}
		LA11: ;
	}
	LA7: ;
	(*dest) = src;
}

static N_INLINE(void, incref_53819)(Cell47505* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_51458(c);
		if (!LOC3) goto LA4;
		rtladdcycleroot_52220(c);
	}
	LA4: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		Cell47505* LOC5;
		if (!!((src == NIM_NIL))) goto LA3;
		LOC5 = 0;
		LOC5 = usrtocell_51440(src);
		incref_53819(LOC5);
	}
	LA3: ;
	{
		Cell47505* LOC10;
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		LOC10 = 0;
		LOC10 = usrtocell_51440((*dest));
		decref_53401(LOC10);
	}
	LA8: ;
	(*dest) = src;
}

static N_INLINE(void, pushCurrentException)(Exception* e) {
	asgnRef((void**) (&(*e).parent), currexception_19439);
	asgnRef((void**) (&currexception_19439), e);
}

N_NOINLINE(NIM_BOOL, isobjslowpath_23734)(TNimType* obj, TNimType* subclass, TNimType** cache) {
	NIM_BOOL result;
	TNimType* x;
{	result = 0;
	x = (*obj).base;
	{
		while (1) {
			if (!!((x == subclass))) goto LA2;
			{
				if (!(x == NIM_NIL)) goto LA5;
				cache[(((NI) 0))- 0] = obj;
				result = NIM_FALSE;
				goto BeforeRet;
			}
			LA5: ;
			x = (*x).base;
		} LA2: ;
	}
	cache[(((NI) 1))- 0] = obj;
	result = NIM_TRUE;
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache) {
	NIM_BOOL result;
{	result = 0;
	{
		if (!(obj == subclass)) goto LA3;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!((*obj).base == subclass)) goto LA7;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA7: ;
	{
		if (!(cache[(((NI) 0))- 0] == obj)) goto LA11;
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA11: ;
	{
		if (!(cache[(((NI) 1))- 0] == obj)) goto LA15;
		result = NIM_TRUE;
		goto BeforeRet;
	}
	LA15: ;
	result = isobjslowpath_23734(obj, subclass, cache);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, quitordebug_20404)(void) {
	exit(((NI) 1));
}

N_NIMCALL(void, raiseexceptionaux_20601)(Exception* e) {
{	{
		if (!!((localraisehook_10018 == NIM_NIL))) goto LA3;
		{
			NIM_BOOL LOC7;
			LOC7 = 0;
			LOC7 = localraisehook_10018(e);
			if (!!(LOC7)) goto LA8;
			goto BeforeRet;
		}
		LA8: ;
	}
	LA3: ;
	{
		if (!!((globalraisehook_10013 == NIM_NIL))) goto LA12;
		{
			NIM_BOOL LOC16;
			LOC16 = 0;
			LOC16 = globalraisehook_10013(e);
			if (!!(LOC16)) goto LA17;
			goto BeforeRet;
		}
		LA17: ;
	}
	LA12: ;
	{
		if (!!((exchandler_19437 == NIM_NIL))) goto LA21;
		{
			NIM_BOOL LOC25;
			LOC25 = 0;
			LOC25 = !((*exchandler_19437).hasRaiseAction);
			if (LOC25) goto LA26;
			LOC25 = (*exchandler_19437).raiseAction.ClEnv? (*exchandler_19437).raiseAction.ClPrc(e, (*exchandler_19437).raiseAction.ClEnv):((TMP26)((*exchandler_19437).raiseAction.ClPrc))(e);
			LA26: ;
			if (!LOC25) goto LA27;
			pushCurrentException(e);
			longjmp((*exchandler_19437).context, ((int) 1));
		}
		LA27: ;
	}
	goto LA19;
	LA21: ;
	{
		if (!(isObjWithCache((*e).Sup.m_type, (&NTI3650), Nim_OfCheck_CACHE1))) goto LA30;
		showerrormessage_19406((*e).name);
		quitordebug_20404();
	}
	goto LA19;
	LA30: ;
	{
		TY21018 buf;
		NI L;
		memset((void*)buf, 0, sizeof(buf));
		L = ((NI) 0);
		{
			if (!((NI)(L + ((NI) 28)) < ((NI) 2000))) goto LA35;
			memcpy(((void*) ((&buf[(L)- 0]))), "Error: unhandled exception: ", ((NI) 28));
			L += ((NI) 28);
		}
		LA35: ;
		{
			if (!!((*e).message == 0)) goto LA39;
			{
				if (!((NI)(L + ((*e).message ? (*e).message->Sup.len : 0)) < ((NI) 2000))) goto LA43;
				memcpy(((void*) ((&buf[(L)- 0]))), ((void*) ((*e).message->data)), ((NI) (((*e).message ? (*e).message->Sup.len : 0))));
				L += ((*e).message ? (*e).message->Sup.len : 0);
			}
			LA43: ;
		}
		LA39: ;
		{
			if (!((NI)(L + ((NI) 2)) < ((NI) 2000))) goto LA47;
			memcpy(((void*) ((&buf[(L)- 0]))), " [", ((NI) 2));
			L += ((NI) 2);
		}
		LA47: ;
		{
			NI LOC51;
			NI LOC54;
			NI LOC55;
			LOC51 = 0;
			LOC51 = strlen((*e).name);
			if (!((NI)(L + LOC51) < ((NI) 2000))) goto LA52;
			LOC54 = 0;
			LOC54 = strlen((*e).name);
			memcpy(((void*) ((&buf[(L)- 0]))), ((void*) ((*e).name)), ((NI) (LOC54)));
			LOC55 = 0;
			LOC55 = strlen((*e).name);
			L += LOC55;
		}
		LA52: ;
		{
			if (!((NI)(L + ((NI) 2)) < ((NI) 2000))) goto LA58;
			memcpy(((void*) ((&buf[(L)- 0]))), "]\012", ((NI) 2));
			L += ((NI) 2);
		}
		LA58: ;
		showerrormessage_19406(((NCSTRING) (buf)));
		quitordebug_20404();
	}
	LA19: ;
	}BeforeRet: ;
}

N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename) {
	(*e).name = ename;
	raiseexceptionaux_20601(e);
}

static N_INLINE(void, sysfatal_15426)(NimStringDesc* message, NimStringDesc* arg) {
	Ioerror3628* e;
	NimStringDesc* LOC1;
	e = 0;
	e = (Ioerror3628*) newObj((&NTI15435), sizeof(Ioerror3628));
	(*e).Sup.Sup.Sup.m_type = (&NTI3628);
	LOC1 = 0;
	LOC1 = rawNewString(message->Sup.len + arg->Sup.len + 0);
appendString(LOC1, message);
appendString(LOC1, arg);
	asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), LOC1);
	raiseException((Exception*)e, "IOError");
}

N_NIMCALL(FILE*, open_15417)(NimStringDesc* filename, NU8 mode, NI bufsize) {
	FILE* result;
	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = open_15403(&result, filename, mode, bufsize);
		if (!!(LOC3)) goto LA4;
		sysfatal_15426(((NimStringDesc*) &TMP27), filename);
	}
	LA4: ;
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_19437;
	exchandler_19437 = s;
}

N_NIMCALL(NI, rawfilesize_81866)(FILE* file) {
	NI result;
	NI oldpos;
	NI LOC1;
	NI LOC2;
	result = 0;
	oldpos = ftell(file);
	LOC1 = 0;
	LOC1 = fseek(file, ((NI) 0), ((NI) 2));
	result = ftell(file);
	LOC2 = 0;
	LOC2 = fseek(file, oldpos, ((NI) 0));
	return result;
}

N_NIMCALL(NimStringDesc*, mnewString)(NI len) {
	NimStringDesc* result;
	result = 0;
	result = rawNewString(len);
	(*result).Sup.len = len;
	return result;
}

N_NIMCALL(NI, readbuffer_15554)(FILE* f, void* buffer, NI len) {
	NI result;
	result = 0;
	result = fread(buffer, ((NI) 1), ((NI) (len)), f);
	return result;
}

N_NIMCALL(NIM_BOOL, endoffile_15454)(FILE* f) {
	NIM_BOOL result;
	int c;
{	result = 0;
	c = fgetc(f);
	ungetc(c, f);
	result = (c < ((NI32) 0));
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, resize_79201)(NI old) {
	NI result;
	result = 0;
	{
		if (!(old <= ((NI) 0))) goto LA3;
		result = ((NI) 4);
	}
	goto LA1;
	LA3: ;
	{
		if (!(old < ((NI) 65536))) goto LA6;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1;
	LA6: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1: ;
	return result;
}

N_NIMCALL(void*, growobj_63403)(void* old, NI newsize, Gcheap49818* gch) {
	void* result;
	Cell47505* ol;
	Cell47505* res;
	void* LOC1;
	NI elemsize;
	NI oldsize;
	result = 0;
	collectct_51807(gch);
	ol = usrtocell_51440(old);
	LOC1 = 0;
	LOC1 = rawalloc_36868((&(*gch).region), (NI)(newsize + ((NI)sizeof(Cell47505))));
	res = ((Cell47505*) (LOC1));
	elemsize = ((NI) 1);
	{
		if (!!(((*(*ol).typ).kind == ((NU8) 28)))) goto LA4;
		elemsize = (*(*(*ol).typ).base).size;
	}
	LA4: ;
	oldsize = (NI)((NI)((*((TGenericSeq*) (old))).len * elemsize) + ((NI) 16));
	memcpy(((void*) (res)), ((void*) (ol)), ((NI) ((NI)(oldsize + ((NI)sizeof(Cell47505))))));
	zeroMem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (res))) + (NU64)(oldsize))) + (NU64)(((NI)sizeof(Cell47505)))))), ((NI) ((NI)(newsize - oldsize))));
	{
		if (!((NU64)((NI)((NU64)((*ol).refcount) >> (NU64)(((NI) 3)))) <= (NU64)(((NI) 1)))) goto LA8;
		{
			NI j;
			Cell47505** d;
			if (!!(((NI)((*ol).refcount & ((NI) 4)) == ((NI) 0)))) goto LA12;
			j = (NI)((*gch).zct.len - ((NI) 1));
			d = (*gch).zct.d;
			{
				while (1) {
					if (!(((NI) 0) <= j)) goto LA15;
					{
						if (!(d[(j)- 0] == ol)) goto LA18;
						d[(j)- 0] = res;
						goto LA14;
					}
					LA18: ;
					j -= ((NI) 1);
				} LA15: ;
			} LA14: ;
		}
		LA12: ;
		{
			NIM_BOOL LOC22;
			LOC22 = 0;
			LOC22 = canbecycleroot_51458(ol);
			if (!LOC22) goto LA23;
			excl_48274((&(*gch).cycleroots), ol);
		}
		LA23: ;
		rawdealloc_43217((&(*gch).region), ((void*) (ol)));
	}
	goto LA6;
	LA8: ;
	{
		(*res).refcount = ((NI) 8);
		decref_53401(ol);
	}
	LA6: ;
	result = celltousr_51422(res);
	return result;
}

N_NIMCALL(void*, growobj_66209)(void* old, NI newsize) {
	void* result;
	result = 0;
	result = growobj_63403(old, newsize, (&gch_49859));
	return result;
}

N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen) {
	NimStringDesc* result;
	result = 0;
	{
		if (!((NI)((*dest).Sup.len + addlen) <= (NI)((*dest).Sup.reserved & ((NI) IL64(9223372036854775807))))) goto LA3;
		result = dest;
	}
	goto LA1;
	LA3: ;
	{
		NI sp;
		NI LOC6;
		void* LOC7;
		LOC6 = 0;
		LOC6 = resize_79201((NI)((*dest).Sup.reserved & ((NI) IL64(9223372036854775807))));
		sp = ((LOC6 >= (NI)((*dest).Sup.len + addlen)) ? LOC6 : (NI)((*dest).Sup.len + addlen));
		LOC7 = 0;
		LOC7 = growobj_66209(((void*) (dest)), (NI)((NI)(((NI)sizeof(TGenericSeq)) + sp) + ((NI) 1)));
		result = ((NimStringDesc*) (LOC7));
		(*result).Sup.reserved = sp;
	}
	LA1: ;
	return result;
}

N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen) {
	NimStringDesc* result;
	NI n;
	result = 0;
	n = ((newlen >= ((NI) 0)) ? newlen : ((NI) 0));
	{
		if (!(n <= (NI)((*s).Sup.reserved & ((NI) IL64(9223372036854775807))))) goto LA3;
		result = s;
	}
	goto LA1;
	LA3: ;
	{
		result = resizeString(s, n);
	}
	LA1: ;
	(*result).Sup.len = n;
	(*result).data[(n)- 0] = 0;
	return result;
}

N_NIMCALL(void*, newObjRC1)(TNimType* typ, NI size) {
	void* result;
	Cell47505* res;
	void* LOC1;
	result = 0;
	collectct_51807((&gch_49859));
	LOC1 = 0;
	LOC1 = rawalloc_36868((&gch_49859.region), (NI)(size + ((NI)sizeof(Cell47505))));
	res = ((Cell47505*) (LOC1));
	(*res).typ = typ;
	(*res).refcount = ((NI) 8);
	result = celltousr_51422(res);
	zeroMem(result, ((NI) (size)));
	return result;
}

N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src) {
	NimStringDesc* result;
	result = 0;
	{
		NI s;
		void* LOC9;
		if (!!((src == NIM_NIL))) goto LA3;
		s = (*src).Sup.len;
		{
			if (!(s < ((NI) 7))) goto LA7;
			s = ((NI) 7);
		}
		LA7: ;
		LOC9 = 0;
		LOC9 = newObjRC1((&strdesc_12203), (NI)((NI)(((NI)sizeof(TGenericSeq)) + s) + ((NI) 1)));
		result = ((NimStringDesc*) (LOC9));
		(*result).Sup.reserved = s;
		(*result).Sup.len = (*src).Sup.len;
		memcpy(((NCSTRING) ((*result).data)), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	}
	LA3: ;
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell47505* c;
	c = usrtocell_51440(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		rtladdzct_53001(c);
	}
	LA3: ;
}

static N_INLINE(void, sysfatal_81210)(NimStringDesc* message) {
	Ioerror3628* e;
	NimStringDesc* LOC1;
	e = 0;
	e = (Ioerror3628*) newObj((&NTI15435), sizeof(Ioerror3628));
	(*e).Sup.Sup.Sup.m_type = (&NTI3628);
	LOC1 = 0;
	LOC1 = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(message);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	raiseException((Exception*)e, "IOError");
}

N_NOINLINE(void, raiseeio_81205)(NimStringDesc* msg) {
	sysfatal_81210(msg);
}

N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src) {
	NimStringDesc* result;
	result = 0;
	{
		if (!!((src == NIM_NIL))) goto LA3;
		{
			if (!!(((NI)((*src).Sup.reserved & ((NI) (IL64(-9223372036854775807) - IL64(1)))) == ((NI) 0)))) goto LA7;
			result = src;
		}
		goto LA5;
		LA7: ;
		{
			result = rawNewStringNoInit((*src).Sup.len);
			(*result).Sup.len = (*src).Sup.len;
			memcpy(((NCSTRING) ((*result).data)), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
		}
		LA5: ;
	}
	LA3: ;
	return result;
}

N_NIMCALL(NimStringDesc*, readallbuffer_81858)(FILE* file) {
	NimStringDesc* result;
	NimStringDesc* buffer;
	result = 0;
	result = copyString(((NimStringDesc*) &TMP30));
	buffer = mnewString(((NI) 4000));
	{
		while (1) {
			NI bytesread;
			bytesread = readbuffer_15554(file, ((void*) ((&buffer->data[((NI) 0)]))), ((NI) 4000));
			{
				if (!(bytesread == ((NI) 4000))) goto LA5;
				result = resizeString(result, buffer->Sup.len + 0);
appendString(result, buffer);
			}
			goto LA3;
			LA5: ;
			{
				buffer = setLengthStr(buffer, ((NI) (bytesread)));
				result = resizeString(result, buffer->Sup.len + 0);
appendString(result, buffer);
				goto LA1;
			}
			LA3: ;
		}
	} LA1: ;
	return result;
}

N_NIMCALL(NimStringDesc*, readallfile_81872)(FILE* file, NI len) {
	NimStringDesc* result;
	NI bytes;
	result = 0;
	result = mnewString(((NI) (len)));
	bytes = readbuffer_15554(file, ((void*) ((&result->data[((NI) 0)]))), ((NI) (len)));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = endoffile_15454(file);
		if (!LOC3) goto LA4;
		{
			if (!(bytes < len)) goto LA8;
			result = setLengthStr(result, ((NI) (bytes)));
		}
		LA8: ;
	}
	goto LA1;
	LA4: ;
	{
		NI LOC11;
		LOC11 = 0;
		LOC11 = ferror(file);
		if (!!((LOC11 == ((NI) 0)))) goto LA12;
		raiseeio_81205(((NimStringDesc*) &TMP29));
	}
	goto LA1;
	LA12: ;
	{
		NimStringDesc* LOC15;
		LOC15 = 0;
		LOC15 = readallbuffer_81858(file);
		result = resizeString(result, LOC15->Sup.len + 0);
appendString(result, LOC15);
	}
	LA1: ;
	return result;
}

N_NIMCALL(NimStringDesc*, readall_15463)(FILE* file) {
	NimStringDesc* result;
	NI len;
	result = 0;
	{
		if (!!((file == stdin))) goto LA3;
		len = rawfilesize_81866(file);
	}
	goto LA1;
	LA3: ;
	{
		len = ((NI) -1);
	}
	LA1: ;
	{
		if (!(((NI) 0) < len)) goto LA8;
		result = readallfile_81872(file, len);
	}
	goto LA6;
	LA8: ;
	{
		result = readallbuffer_81858(file);
	}
	LA6: ;
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_19437 = (*exchandler_19437).prev;
}
N_NIMCALL(void, TMP31)(void* p, NI op) {
	Reraiseerror3660* a;
	a = (Reraiseerror3660*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
}

static N_INLINE(void, sysfatal_21217)(NimStringDesc* message) {
	Reraiseerror3660* e;
	NimStringDesc* LOC1;
	e = 0;
	e = (Reraiseerror3660*) newObj((&NTI21224), sizeof(Reraiseerror3660));
	(*e).Sup.Sup.m_type = (&NTI3660);
	LOC1 = 0;
	LOC1 = (*e).Sup.message; (*e).Sup.message = copyStringRC1(message);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	raiseException((Exception*)e, "ReraiseError");
}

N_NIMCALL(void, reraiseException)(void) {
	{
		if (!(currexception_19439 == NIM_NIL)) goto LA3;
		sysfatal_21217(((NimStringDesc*) &TMP32));
	}
	goto LA1;
	LA3: ;
	{
		raiseexceptionaux_20601(currexception_19439);
	}
	LA1: ;
}

N_NIMCALL(NimStringDesc*, readfile_15466)(NimStringDesc* filename) {
	NimStringDesc* volatile result;
	FILE* f;
	TSafePoint TMP28;
	result = 0;
	f = open_15417(filename, ((NU8) 0), ((NI) -1));
	pushSafePoint(&TMP28);
	TMP28.status = setjmp(TMP28.context);
	if (TMP28.status == 0) {
		result = readall_15463(f);
		popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		fclose(f);
	}
	if (TMP28.status != 0) reraiseException();
	return result;
}
N_NIMCALL(void, TMP33)(void* p, NI op) {
	Indexerror3652* a;
	a = (Indexerror3652*)p;
	nimGCvisit((void*)(*a).Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.message, op);
	nimGCvisit((void*)(*a).Sup.trace, op);
}
N_NIMCALL(void, TMP36)(void* p, NI op) {
	TY92050* a;
	NI LOC1;
	a = (TY92050*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}
N_NIMCALL(void, TMP38)(void* p, NI op) {
	Overflowerror3640* a;
	a = (Overflowerror3640*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
}

static N_INLINE(void, sysfatal_23862)(NimStringDesc* message) {
	Overflowerror3640* e;
	NimStringDesc* LOC1;
	e = 0;
	e = (Overflowerror3640*) newObj((&NTI23869), sizeof(Overflowerror3640));
	(*e).Sup.Sup.Sup.m_type = (&NTI3640);
	LOC1 = 0;
	LOC1 = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(message);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	raiseException((Exception*)e, "OverflowError");
}

N_NOINLINE(void, raiseOverflow)(void) {
	sysfatal_23862(((NimStringDesc*) &TMP39));
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, mulInt)(NI a, NI b) {
	NI result;
	NF resasfloat;
	NF floatprod;
{	result = 0;
	resasfloat = 0;
	floatprod = 0;
	result = (NI)((NU64)(a) * (NU64)(b));
	floatprod = ((NF)(((double) (a))) * (NF)(((double) (b))));
	resasfloat = ((double) (result));
	{
		if (!(resasfloat == floatprod)) goto LA3;
		goto BeforeRet;
	}
	LA3: ;
	{
		if (!(((NF)(3.2000000000000000e+01) * (NF)((((NF)(resasfloat) - (NF)(floatprod)) > 0? (((NF)(resasfloat) - (NF)(floatprod))) : -(((NF)(resasfloat) - (NF)(floatprod)))))) <= (floatprod > 0? (floatprod) : -(floatprod)))) goto LA7;
		goto BeforeRet;
	}
	LA7: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void*, newSeq)(TNimType* typ, NI len) {
	void* result;
	NI size;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = mulInt(len, (*(*typ).base).size);
	size = addInt(LOC1, ((NI) 16));
	result = newObj(typ, size);
	(*((TGenericSeq*) (result))).len = len;
	(*((TGenericSeq*) (result))).reserved = len;
	return result;
}

N_NIMCALL(TY92050*, newseq_92045)(NI len) {
	TY92050* result;
	result = 0;
	result = (TY92050*) newSeq((&NTI92050), len);
	return result;
}

N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize) {
	TGenericSeq* result;
	result = 0;
	result = seq;
	{
		void* LOC5;
		if (!((NI)((*result).reserved & ((NI) IL64(9223372036854775807))) <= (*result).len)) goto LA3;
		(*result).reserved = resize_79201((NI)((*result).reserved & ((NI) IL64(9223372036854775807))));
		LOC5 = 0;
		LOC5 = growobj_66209(((void*) (result)), (NI)((NI)(elemsize * (*result).reserved) + ((NI) 16)));
		result = ((TGenericSeq*) (LOC5));
	}
	LA3: ;
	return result;
}

N_NIMCALL(void, write_15497)(FILE* f, NIM_CHAR c) {
	putc(c, f);
}
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void) {
	TNimType LOC1;
	nimvm_5751 = NIM_FALSE;
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.size = ((NI) 8);
	LOC1.kind = ((NU8) 28);
	LOC1.flags = 2;
	strdesc_12203 = LOC1;
	initallocator_11601();
	initStackBottom();
	initgc_11401();
	registersignalhandler_23002();
}

NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void) {
static TNimNode* TMP23[4];
static TNimNode TMP0[13];
NTI3608.size = sizeof(TNimObject);
NTI3608.kind = 17;
NTI3608.base = 0;
NTI3608.flags = 1;
TMP0[0].len = 0; TMP0[0].kind = 2;
NTI3608.node = &TMP0[0];
NTI3624.size = sizeof(Exception);
NTI3624.kind = 17;
NTI3624.base = (&NTI3608);
TMP23[0] = &TMP0[2];
NTI10010.size = sizeof(Exception*);
NTI10010.kind = 22;
NTI10010.base = (&NTI3624);
NTI10010.marker = TMP24;
TMP0[2].kind = 1;
TMP0[2].offset = offsetof(Exception, parent);
TMP0[2].typ = (&NTI10010);
TMP0[2].name = "parent";
TMP23[1] = &TMP0[3];
NTI140.size = sizeof(NCSTRING);
NTI140.kind = 29;
NTI140.base = 0;
NTI140.flags = 3;
TMP0[3].kind = 1;
TMP0[3].offset = offsetof(Exception, name);
TMP0[3].typ = (&NTI140);
TMP0[3].name = "name";
TMP23[2] = &TMP0[4];
NTI138.size = sizeof(NimStringDesc*);
NTI138.kind = 28;
NTI138.base = 0;
NTI138.flags = 2;
TMP0[4].kind = 1;
TMP0[4].offset = offsetof(Exception, message);
TMP0[4].typ = (&NTI138);
TMP0[4].name = "msg";
TMP23[3] = &TMP0[5];
TMP0[5].kind = 1;
TMP0[5].offset = offsetof(Exception, trace);
TMP0[5].typ = (&NTI138);
TMP0[5].name = "trace";
TMP0[1].len = 4; TMP0[1].kind = 2; TMP0[1].sons = &TMP23[0];
NTI3624.node = &TMP0[1];
NTI3626.size = sizeof(Systemerror3626);
NTI3626.kind = 17;
NTI3626.base = (&NTI3624);
TMP0[6].len = 0; TMP0[6].kind = 2;
NTI3626.node = &TMP0[6];
NTI3628.size = sizeof(Ioerror3628);
NTI3628.kind = 17;
NTI3628.base = (&NTI3626);
TMP0[7].len = 0; TMP0[7].kind = 2;
NTI3628.node = &TMP0[7];
NTI15435.size = sizeof(Ioerror3628*);
NTI15435.kind = 22;
NTI15435.base = (&NTI3628);
NTI15435.marker = TMP25;
NTI3650.size = sizeof(Outofmemerror3650);
NTI3650.kind = 17;
NTI3650.base = (&NTI3626);
TMP0[8].len = 0; TMP0[8].kind = 2;
NTI3650.node = &TMP0[8];
NTI3660.size = sizeof(Reraiseerror3660);
NTI3660.kind = 17;
NTI3660.base = (&NTI3624);
TMP0[9].len = 0; TMP0[9].kind = 2;
NTI3660.node = &TMP0[9];
NTI21224.size = sizeof(Reraiseerror3660*);
NTI21224.kind = 22;
NTI21224.base = (&NTI3660);
NTI21224.marker = TMP31;
NTI3652.size = sizeof(Indexerror3652);
NTI3652.kind = 17;
NTI3652.base = (&NTI3624);
TMP0[10].len = 0; TMP0[10].kind = 2;
NTI3652.node = &TMP0[10];
NTI135415.size = sizeof(Indexerror3652*);
NTI135415.kind = 22;
NTI135415.base = (&NTI3652);
NTI135415.marker = TMP33;
NTI104.size = sizeof(NI);
NTI104.kind = 31;
NTI104.base = 0;
NTI104.flags = 3;
NTI136.size = sizeof(NIM_CHAR);
NTI136.kind = 2;
NTI136.base = 0;
NTI136.flags = 3;
NTI92050.size = sizeof(TY92050*);
NTI92050.kind = 24;
NTI92050.base = (&NTI136);
NTI92050.flags = 2;
NTI92050.marker = TMP36;
NTI3636.size = sizeof(Arithmeticerror3636);
NTI3636.kind = 17;
NTI3636.base = (&NTI3624);
TMP0[11].len = 0; TMP0[11].kind = 2;
NTI3636.node = &TMP0[11];
NTI3640.size = sizeof(Overflowerror3640);
NTI3640.kind = 17;
NTI3640.base = (&NTI3636);
TMP0[12].len = 0; TMP0[12].kind = 2;
NTI3640.node = &TMP0[12];
NTI23869.size = sizeof(Overflowerror3640*);
NTI23869.kind = 22;
NTI23869.base = (&NTI3640);
NTI23869.marker = TMP38;
}

